lib/services/contextServer.js

Updates to modify the status were issued with the ID of the device, instead of its `name` so there was a bug when the two of them were different.

FIX Entity ID for virtual attributes '_status'

---

lib/services/deviceRegistryMemory.js

Fix callback in the store() function of the Memory Registry (didn't return the device).

FIX Store callback do not return device itself

---

CHANGES_NEXT_RELEASE
lib/services/ngsiParser.js

Return a meaningful JSON object in ENTITY_GENERIC_ERROR, instead of a concatenation of two of the fields.

FIX Return menaingful JSON error

---

bin/iotAgentTester.js

Remove device operation in the IoT Agent client won't work through authenticated PEP Proxies, as no fiware-service and fiware-servicepath headers were sent.

FIX Add service and subservice headers in remove device

---

CHANGES_NEXT_RELEASE
lib/services/devices/deviceRegistryMongoDB.js
lib/services/groups/groupRegistryMongoDB.js

Queries to the MongoDB registries based on service was not working (the condition was stablished after the query was executed).

FIX Queries to the registries based on service

---

README.md
lib/constants.js
lib/services/common/iotManagerService.js
test/unit/general/iotam-autoregistration-test.js

Move defaultResource attribute from the IoTManager section to config root (as it may be used in situations where an IoTManager is not needed).

Move defaultResource attribute to config root

---

lib/services/northBound/deviceProvisioningServer.js

Missing transport attribute in MongoDB registers due to the order of insertion in the device provisioning handlers: modifying the value in the device object doesn't reflect in MongoDB (as the save instruction is executed before the handler).

FIX Missing transport in MongoDB registers

---

docker/Dockerfile
docker/aclfile
docker/startMosquitto.sh

Create a Mosquitto Docker image to use with the IoT Agents accepting MQTT.

ADD Mosquitto Docker files

---

CHANGES_NEXT_RELEASE
package.json

Prepares for the next development cycle. Similar to what it was done last time, see PR https://github.com/telefonicaid/iotagent-node-lib/pull/518/files

Step: 2.5.0 -> 2.5.0-next

---

CHANGES_NEXT_RELEASE
lib/services/commands/commandService.js

Fix logs like:
```
time=2017-12-19T07:46:13.725Z | lvl=DEBUG | corr=7157c7c7-796a-4ff8-bbfe-443fdc9ef606 | trans=7157c7c7-796a-4ff8-bbfe-443fdc9ef606 | op=IoTAgentNGSI.CommandService | srv=tsol_poc | subsrv=/pruebas | msg=Removing command [%] from device [disp4] | comp=IoTAgent respuesta
```

fix command name in logs

---

CHANGES_NEXT_RELEASE
package.json

Previous version (2.2.10) is already deprecated.
Maybe this update solves issue https://github.com/telefonicaid/iotagent-node-lib/issues/577

Update mongodb dependence in package.json

---

README.md
doc/index.md
mkdocs.yml

Currently this project is not building CSS styled documentation. This PR  creates an initial Readthedocs template and updates the README links to display the CSS styled documentation rather than raw GFM markdown. The styled documentation is a lot easier to navigate.
* Create mkdocs.yml file
* Amend README to link to styled documentation
* Add docs-passing badge
* Add root topic to docs
For this PR is to be successful, the project must also be enabled on readthedocs.

Create Readthedocs  CSS styled documentation

---

CHANGES_NEXT_RELEASE
lib/services/devices/deviceService.js
lib/services/groups/groupService.js
lib/services/ngsi/ngsiService.js

An env var like:
```
- IOTA_SINGLE_MODE=false
```
is not detected properly,  by:
```
if (config.getConfig().singleConfigurationMode)
```
so i need to check against boolean value 
This is happening in several parts of the library, probably they work fine with node 0.10 but not with node 4 or 6

check boolean configuration fields explicitly againts right boolean value

---

README.md
doc/Contribution.md
doc/expressionLanguage.md
doc/howto.md
doc/installationguide.md
doc/northboundinteractions.md
doc/operations.md
doc/usermanual.md

* The link to readthedocs on the main readme has been corrected
* Readthedocs is unable to handle `<a href="xx">` anchor tags, this also messes up the sidebar in readthedocs. These have been removed.
* Table of Contents (ToC) has been regenerated for each documentation file.
* Readthedocs cannot handle fenced code blocks - an extra linefeed has been added where necessary.
To be honest the ToC is both confusing and unnecessary for the readthedocs documentation - it is generated on the sidebar automatically. Second level headings are also not indented by readthedocs
My preference would be to remove the extra table of contents on each readthedocs, but I have done a 1-to-1 replacement for now, therefore some pages have a ToC, others do not. Some have a one level ToC, others a 2 level ToC.

Improve readability of readthedocs documentation.

---

CHANGES_NEXT_RELEASE
lib/services/groups/groupService.js

https://github.com/telefonicaid/iotagent-node-lib/issues/633
after increase mongodb driver version cursor now returns a non empty foundGroup like:
foundGroup {"count":0,"services":[]}

check foundGroup count in generateDuplicateHandler

---

lib/services/common/alarmManagement.js
lib/services/groups/groupRegistryMongoDB.js

Related with previous fix:
Fix: undefined MONGO-ALARMS in logs due to a bad mongo query. (#630, #577)

replace undefined by current alarm description

---

CHANGES_NEXT_RELEASE
doc/expressionLanguage.md
lib/plugins/expressionParser.js
test/unit/ngsiv2/examples/contextRequests/updateContextExpressionPlugin1.json
test/unit/ngsiv2/examples/contextRequests/updateContextExpressionPlugin11.json
test/unit/ngsiv2/examples/contextRequests/updateContextExpressionPlugin12.json
test/unit/ngsiv2/examples/contextRequests/updateContextExpressionPlugin13.json
test/unit/ngsiv2/examples/contextRequests/updateContextExpressionPlugin2.json
test/unit/ngsiv2/examples/contextRequests/updateContextExpressionPlugin3.json
test/unit/ngsiv2/examples/contextRequests/updateContextExpressionPlugin4.json
test/unit/ngsiv2/examples/contextRequests/updateContextExpressionPlugin8.json
test/unit/ngsiv2/expressions/expressionBasedTransformations-test.js

With NGSIv2, casting in expression plugin considers that attributes with Integer and Float values use `type Number.
This follows:
- https://www.w3schools.com/js/js_json_datatypes.asp, JSON native type for Integer or Floats is Number.
- Partial Representations section of http://telefonicaid.github.io/fiware-orion/api/v2/stable/
Unit tests are modified (and passed) properly.

Fixes #643

---

doc/Contribution.md
doc/howto.md
doc/northboundinteractions.md
doc/operations.md
doc/usermanual.md

After discussion with @dcalvoalonso 
With standard English usage, the “bound”  suffix in implies a direction e.g “Homeward bound" means "going **towards** my home”, therefore “Southbound” means "going **towards** the South”
In contrast, the phrase "to the North of” does not imply direction, it implies relative location — you can be to the North of a town, but travelling Southbound - i.e. towards the city.
The main common usage of Northbound/Southbound is found with motorway traffic reports e.g. “the Northbound carriageway is blocked"
Therefore the following usage is correct common English, and the existing documents should be corrected to use it: 
* Traffic **to the South of** the IoT Agent refers to the exchange of information and commands between a device and an IoT Agent (Native …

Clarified North/South, removed anchors, added code highlights

---

CHANGES_NEXT_RELEASE
lib/services/groups/groupService.js
lib/services/northBound/deviceGroupAdministrationServer.js
test/unit/examples/contextAvailabilityRequests/unregisterProvisionedDevice.json
test/unit/provisioning/device-group-api-test.js

@fgalan @dcalvoalonso 
this is an attempt to fix #596, but i need a some support in understanding why i get an ECONNECT error from the nock server when unregistration are sent to context broker.
i supposed that:
```
contextBrokerMock = nock('http://192.168.1.1:1026')
.matchHeader('fiware-service', 'TestService')
.matchHeader('fiware-servicepath', '/testingPath')
.post('/NGSI9/registerContext')
.reply(200,
utils.readExampleFile(
'./test/unit/examples/contextAvailabilityResponses/unregisterDevice1Success.json'));
```
would have been the only thing needed, but apparently something is still wrong (when using a real context broker there is no issue).
thx.

remove devices related to a service when device=true option used (see #596)

---

lib/model/dbConn.js

fix https://github.com/telefonicaid/iotagent-node-lib/pull/684#issuecomment-435838531
According with 
https://docs.mongodb.com/manual/reference/connection-string/#connections-connection-options
example:
```
mongodb://db1.example.net:27017,db2.example.net:2500/?replicaSet=test&connectTimeoutMS=300000
```

add replicaSet in uri

---

doc/expressionLanguage.md
doc/howto.md
doc/northboundinteractions.md
doc/operations.md
doc/usermanual.md

* The ToC is suppressed with the ReadtheDocs CSS
* The ToC Header cannot be suppressed without CSS3
Therefore the title of the ToC should be removed to avoid confusion

Remove `##Index` from ToC since it is not required - fixes #648

---

lib/services/devices/deviceService.js
lib/services/devices/registrationUtils.js
lib/services/ngsi/ngsiService.js
test/unit/general/deviceService-test.js
test/unit/ngsiv2/general/deviceService-test.js
test/unit/ngsiv2/plugins/multientity-plugin_test.js
test/unit/ngsiv2/provisioning/singleConfigurationMode-test.js
test/unit/provisioning/singleConfigurationMode-test.js

As it is explained in https://github.com/telefonicaid/iotagent-json/pull/353#issuecomment-442858364, there is an inconsistent use of the field `cbhost` of groups. Although thanks to https://github.com/telefonicaid/iotagent-node-lib/pull/697/files, it is used to create the initial entity in the CB using NGSIv2, to update entities and to send unregistration requests, it was not used to send the subscription request using NGSIv2, nor some of the previously mentioned operations using NSGSIv1.
This PR implements these missing aspects and modified the corresponding unit tests.

Implements missing aspects of use of group's cbhost

---

README.md
docs/roadmap.md

Fixes https://github.com/telefonicaid/iotagent-node-lib/issues/756
@dcalvoalonso could you have a look and provide LGTM if ok, pls? Thanks!

Add roadmap document

---

CHANGES_NEXT_RELEASE
doc/installationguide.md
lib/commonConfig.js

Related: https://github.com/telefonicaid/iotagent-ul/pull/339#issuecomment-476255597
This PR adds Docker `ENV` parameters for the following parts of the config:
| Environment variable      | Configuration attribute             |
|:------------------------- |:----------------------------------- |
| IOTA_AUTH_URL             | authentication.url                  |
| IOTA_AUTH_CLIENT_ID       | authentication.clientId             |
| IOTA_AUTH_CLIENT_SECRET   | authentication.clientSecret         |
| IOTA_AUTH_TOKEN_PATH      | authentication.tokenPath            |
Furthermore `IOTA_CB_HOST` and `IOTA_CB_PORT` should always update their relevant part of the config regardless of whether `IOTA_CB_URL` is set, as the debug statements regarding the initialization (e.g. _overriding_ `CB_HOST`) …

Add missing ENV parameters

---

CHANGES_NEXT_RELEASE
doc/operations.md
lib/model/dbConn.js

This PR should fix reconnection with MongoDBs when using single MongoDBs instances (e.g. for basic or demo installations). In this scenario, if the connection to the MongoDB server is lost and the IoTAgent is not able to reconnect again in a short period of time, the IoTAgent node lib will never reconnect again to MongoDB leaving the IoTAgent in a zombi status. 
This can be easily reproduced by shutting down the MongoDB server while the IoTAgent is running, leaving the MongoDB server down enough time and starting it again.
This happens because the IoTAgent node libe is not listening to the `reconnectFailed` event. Mongoose will try to reconnect every `reconnectInterval` milliseconds for `reconnectTries` times before raising the `reconnectFailed` event (See [mongoose's …

[WIP] Fix reconnection problems with single mongo db instances

---

CHANGES_NEXT_RELEASE
lib/commonConfig.js
lib/services/common/iotManagerService.js

Potential fix/workaround for https://github.com/telefonicaid/iotagent-ul/issues/320
When checking to see if `IOTA_DEFAULT_RESOURCE` is set, deliberately check for `undefined` rather than general truthiness, since a zero-length string is also `false` This allows docker-compose users to set the default resource to blank `''` using an `ENV` as shown:
```yaml
iot-agent:
image: iot-agent
depends_on:
- mongo-db
- mosquitto
networks:
- default
expose:
- "4041"
ports:
- "4041:4041"
environment:
...etc
- IOTA_MQTT_HOST=mosquitto # The host name of the MQTT Broker
- IOTA_MQTT_PORT=1883 # The port the MQTT Broker is listening on to receive topics
- IOTA_DEFAULT_RESOURCE= # Default is blank. I'm using MQTT so I don't need a resource
```
This means that an MQTT device can be successfully provisioned …

Allow blank as an override for defaultResource

---

CHANGES_NEXT_RELEASE
lib/services/devices/deviceService.js

The function `executeWithSecurity()` has the following logic:
```javascript
var typeInformation;
if (deviceGroup) {
typeInformation = deviceGroup;
} else {
typeInformation = config.getConfig().types[deviceData.type];
}
if (config.getConfig().authentication && config.getConfig().authentication.enabled) {
var security = config.getSecurityService();
if (typeInformation && typeInformation.trust) {
///  ...etc
} else {
callback(new errors.SecurityInformationMissing(typeInformation.type));
}
// etc ...
```
If security is properly configured and  a device is provisioned which does not belong to an existing group (neither in the config, nor in a previsioned group) then:
```javascript
typeInformation = config.getConfig().types[deviceData.type] = null;
```
and the error call back will null pointer …

Fix #829 - Add null check

---

CHANGES_NEXT_RELEASE

For traceability, we add the corresponding issue nunber in CHANGEX_NEXT_RELEASE whenever is possible. I missed this in the PR #833 review.
CC: @jason-fox

Add missing issue number in CHANGES_NEXT_RELEASE

---

CHANGES_NEXT_RELEASE
lib/plugins/pluginUtils.js
lib/plugins/timestampProcessPlugin.js
lib/services/commands/commandRegistryMongoDB.js
lib/services/devices/deviceService.js
lib/services/ngsi/ngsiService.js
test/unit/ngsiv2/examples/contextRequests/updateContextCompressTimestamp2.json
test/unit/ngsiv2/examples/contextRequests/updateContextMultientityPlugin8.json
test/unit/ngsiv2/examples/contextRequests/updateContextStaticAttributesMetadata.json
test/unit/ngsiv2/ngsiService/active-devices-test.js
test/unit/ngsiv2/plugins/compress-timestamp-plugin_test.js
test/unit/ngsiv2/plugins/multientity-plugin_test.js

I want to be able to add metadata when provisioning an IoT Agent, so that the units of measurement can be placed into the resultant entity.
e.g.:
```json
{
"entity_type": "Lamp",
"resource":    "/iot/d",
"protocol":    "PDI-IoTA-UltraLight",
..etc
"commands": [ 
{"name": "on","type": "command"},
{"name": "off","type": "command"}
],
"attributes": [
{"object_id": "s", "name": "state", "type":"Text"},
{"object_id": "l", "name": "luminosity", "type":"Integer",
"metadata":{
"unitCode":{"type": "Text", "value" :"CAL"}
}
}
],
"static_attributes": [
{"name": "category", "type":"Text", "value": ["actuator","sensor"]},
{"name": "controlledProperty", "type": "Text", "value": ["light"],
"metadata":{
"includes":{"type": "Text", "value" :["state", "luminosity"]},
"alias":{"type": "Text", "value" …
```

Add NGSIv2 metadata support to device provisioned attributes

---

CHANGES_NEXT_RELEASE
lib/plugins/attributeAlias.js
test/unit/ngsiv2/examples/contextRequests/updateContextAliasPlugin1.json
test/unit/ngsiv2/examples/contextRequests/updateContextAliasPlugin2.json
test/unit/ngsiv2/plugins/alias-plugin_test.js

Amend the `aliasAttribute` plugin to do the following:
- copy over `metadata` if found in provisioning data
- update two tests to use `metadata` in provisioning.
The other eight `aliasAttribute` test cases have not been updated, so that the negative case - alias without `metadata` - is still covered.

Add NGSIv2 metadata support to attributeAlias plugin

---

lib/model/dbConn.js

With this pr the mongodb authentication is fixed. Here I have incorporated the suggestions of @srrspace mentioned here https://github.com/telefonicaid/iotagent-node-lib/commit/13f67ead5327ebdcd97a7b7858ac64a361ad9655 . Username, Password, AuthSource and ReplicaSet are no longer written in the connection string but in the options. The option parameter are looked up here http://mongodb.github.io/node-mongodb-native/2.2/api/MongoClient.html#connect .
I tested it with a mongodb with replicaset and authentication and without replicaset and authentication.

fix the mongodb authentication

---

CHANGES_NEXT_RELEASE
README.md
doc/expressionLanguage.md
doc/installationguide.md
lib/commonConfig.js
lib/fiware-iotagent-lib.js
lib/model/Device.js
lib/model/Group.js
lib/plugins/expressionPlugin.js
lib/plugins/jexlParser.js
lib/templates/createDevice.json
lib/templates/deviceGroup.json
lib/templates/updateDevice.json
package.json
test/unit/expressions/expressionCombinedTransformations-test.js
test/unit/expressions/jexlBasedTransformations-test.js
test/unit/expressions/jexlExpression-test.js
test/unit/ngsiv2/expressions/expressionCombinedTransformations-test.js
test/unit/ngsiv2/expressions/jexlBasedTransformations-test.js

This pull request provide a new plugin to integrate JEXL (https://github.com/TomFrost/jexl), a library that provides a rich javascript expression language, as an alternative to the native IoTAgent Lib expression language.

Provide an alternative expression plugin

---

CHANGES_NEXT_RELEASE
README.md
doc/expressionLanguage.md
doc/installationguide.md
lib/commonConfig.js
lib/fiware-iotagent-lib.js
lib/model/Device.js
lib/model/Group.js
lib/plugins/expressionPlugin.js
lib/plugins/jexlParser.js
lib/templates/createDevice.json
lib/templates/deviceGroup.json
lib/templates/updateDevice.json
package.json
test/unit/expressions/expressionCombinedTransformations-test.js
test/unit/expressions/jexlBasedTransformations-test.js
test/unit/expressions/jexlExpression-test.js
test/unit/ngsiv2/expressions/expressionCombinedTransformations-test.js
test/unit/ngsiv2/expressions/jexlBasedTransformations-test.js

The final land for the PR #800 into master. Some adjustments done in CNR file
CC: @chicco785

Provide an alternative expression plugin (final landing)

---

CHANGES_NEXT_RELEASE
doc/expressionLanguage.md

Merge after PR #800 (just in case some extra adjust is required)

FIX improve expression plugin documentation

---

lib/plugins/jexlParser.js

bug in previos PR https://github.com/telefonicaid/iotagent-node-lib/pull/861
to avoid json expression will be transformed to [object Object]
```
{
"name" : "mylocation",
"type" : "geo:json",
"expression" : "{type: \"Point\", coordinates: [lat,lon]}"
}
```
No CNR update is needed since is reopen a previous PR

fix jexl transformation expression when is  a JSON based value

---

lib/services/northBound/contextServer-NGSI-LD.js
test/unit/ngsi-ld/examples/contextProviderResponses/queryInformationResponse.json
test/unit/ngsi-ld/examples/contextProviderResponses/queryInformationResponseEmptyAttributes.json
test/unit/ngsi-ld/examples/contextProviderResponses/queryInformationStaticAttributesResponse.json
test/unit/ngsi-ld/lazyAndCommands/lazy-devices-test.js

When updating an actuator and then querying the result, the response from the IoT Agent was invalid.
The forwarded query:
```console
curl -iX GET  'http://localhost:4041/ngsi-ld/v1/entities/urn:ngsi-ld:Device:water001?attrs=on,off'
```
was returning an array:
```json
[
{
"type": "Device",
"id": "urn:ngsi-ld:Device:water001",
"on": {
"type": "command",
"value": ""
},
"off": {
"type": "command",
"value": ""
}
}
]
```
It should have returned a single entity:
```json
{
"type": "Device",
"id": "urn:ngsi-ld:Device:water001",
"on": {
"type": "command",
"value": ""
},
"off": {
"type": "command",
"value": ""
}
}
```
Note that currently only single entities (e.g. `/urn:ngsi-ld:Device:water001`) can be *requested* and returned, however the code to deal with multiple entities (e.g. …

Bug fix - command result.

---

lib/constants.js

Add GeoProperty, Point , Date and Time types since GeoJSON is native in NGSI-LD. 
The following provisioning statement is valid:
```console
curl -L -X POST 'http://localhost:4041/iot/services' \
-H 'fiware-service: openiot' \
-H 'fiware-servicepath: /' \
--data-raw '{
"services": [
{
"apikey": "4jggokgpepnvsb2uv4s40d59ov",
"cbroker": "http://orion:1026",
"entity_type": "Device",
"resource": "/iot/d",
"attributes": [
{
"object_id":"bpm",
"type":"Float",
"name": "heartRate"
},
{
"object_id": "s",
"name": "status",
"type": "String"
},
{
"object_id": "gps",
"name": "location",
"type": "geo:point"
}
]
}
]
}'
```
The following *equivalent* provisioning statement *should* be valid for NGSI-LD:
```console
curl -L -X POST 'http://localhost:4041/iot/services' \
-H 'fiware-service: openiot' \
-H …
```

Add common NGSI-LD constants

---

lib/services/devices/devices-NGSI-LD.js
test/unit/ngsi-ld/ngsiService/active-devices-test.js
test/unit/ngsi-ld/provisioning/device-provisioning-api_test.js

- In v1.2.1, response code is 200 (the current official version)
- In v1.3.1, response code is 201 if some created entities, 204 if just updated existing (the soon to be released version)
This PR aims at handling these differences in the response code when creating or updating entities in the context broker.

fix: NGSI-LD v1.2.1 and v1.3.1 success response codes on entities creation / update

---

lib/services/devices/devices-NGSI-LD.js
test/unit/ngsi-ld/ngsiService/active-devices-test.js
test/unit/ngsi-ld/provisioning/device-provisioning-api_test.js

Fixing Linting failure from merge of #887 
```text
lib/services/devices/devices-NGSI-LD.js: line 83, col 121, Line is too long.
lib/services/devices/devices-NGSI-LD.js: line 83, col 84, Expected '===' and instead saw '=='.
lib/services/devices/devices-NGSI-LD.js: line 83, col 114, Expected '===' and instead saw '=='.
lib/services/devices/devices-NGSI-LD.js: line 129, col 84, Expected '===' and instead saw '=='.
test/unit/ngsi-ld/ngsiService/active-devices-test.js: line 542, col 42, Strings must use singlequote.
test/unit/ngsi-ld/ngsiService/active-devices-test.js: line 542, col 58, Strings must use singlequote.
test/unit/ngsi-ld/provisioning/device-provisioning-api_test.js: line 626, col 126, Line is too long.
test/unit/ngsi-ld/provisioning/device-provisioning-api_test.js: line 677, col …
```

Fix merge conflicts again again.

---

CHANGES_NEXT_RELEASE
lib/errors.js
lib/services/groups/groupRegistryMongoDB.js

When this error applies, only this log is printer.
```
iot-iota-json               | time=2020-09-11T07:59:14.361Z | lvl=ERROR | corr=n/a | trans=n/a | op=IoTAgentNGSI.Alarms | srv=smartcity | subsrv=/ | msg=Raising [MONGO-ALARM]: {"name":"DEVICE_GROUP_NOT_FOUND","message":"Couldn\t find device group","code":404} | comp=IoTAgent
```
More details is desirable.
https://github.com/telefonicaid/iotagent-node-lib/blob/master/lib/services/groups/groupRegistryMongoDB.js#L167
https://github.com/telefonicaid/iotagent-node-lib/blob/master/lib/services/groups/groupRegistryMongoDB.js#L238

log details when device group not found

---

CHANGES_NEXT_RELEASE
lib/commonConfig.js
package.json
test/unit/ngsiv2/general/startup-test.js

Currently the Docker Secret and Password processing lies within an entrypoint bash file e.g.: 
https://github.com/telefonicaid/iotagent-ul/blob/master/docker/entrypoint.sh
From a security perspective this isn't ideal, as the dockerization will be Node.js + bash script combination. This means the application can never be run *Distroless* as it relies on bash, and therefore offers a wider attack profile.
https://medium.com/@dwdraju/distroless-is-for-security-if-not-for-size-6eac789f695f
This PR moves as much of the bash scripting as possible inside the Node app, which will allow for the creation of smaller, securer *Distroless* Docker images.
A sample *Distroless* build can be found here: https://github.com/FIWARE/tutorials.Step-by-Step/blob/master/docker/Dockerfile 
```Dockerfile
RUN sed …
```

Security improvement: Move secret support within Node

---

lib/commonConfig.js
package.json

Remove   @cloudreach/docker-secrets replace with custom code.
- Add try/catch
- Make Secrets locations configurable

Fix secrets for RedHat systems.

---

lib/services/devices/devices-NGSI-LD.js
test/unit/ngsi-ld/provisioning/device-update-registration_test.js
test/unit/ngsi-ld/provisioning/updateProvisionedDevices-test.js

Hi all,
As discussed in https://github.com/telefonicaid/iotagent-node-lib/pull/888 (with a lot of delay, sorry for that), here is the PR to activate update mode when calling the batch upsert NGSI-LD API to update entities.
Default mode for batch upsert is to replace entities, which does not exactly match with what we want to do (basically updating a value measured by a sensor).

feat: use update mode of batch upsert when updating NGSI-LD entities

---

CHANGES_NEXT_RELEASE
doc/installationguide.md
lib/commonConfig.js
lib/services/northBound/deviceProvisioningServer.js
lib/services/northBound/northboundServer.js
lib/templates/createDeviceLax.json
lib/templates/updateDeviceLax.json

- Add IOTA_RELAX_TEMPLATE_VALIDATION env.
- Add switch for Lax/Strict ObjectId templating
- Amend documentation.
@gabrieledeluca - would this work for you?

Add lax validation mode for OPC-UA IoT Agent

---

README.md
doc/api.md
doc/development.md
package.json

Add missing text-lint package. The latest text-lint complains if you add something like *comments* in the config, but don't include the module.

Fix issues with Markdown Lint GitHub Action

---

lib/commonConfig.js

Introduced by https://github.com/telefonicaid/iotagent-node-lib/pull/947
All these CI test are failing:
```
>>> features.TS02_iotaflows.004_iotajsonhttp2cb.IOT-iota004 IOTA_JSON with HTTP binding to CB through IOTA.SC_1 Simple measure received thought IOTA_JSON and HTTP binding -- @1.1 2 min 17 sec 3
>>> features.TS02_iotaflows.004_iotajsonhttp2cb.IOT-iota004 IOTA_JSON with HTTP binding to CB through IOTA.SC_1 Simple measure received thought IOTA_JSON and HTTP binding -- @1.2 2 min 19 sec 3
>>> features.TS02_iotaflows.004_iotajsonhttp2cb.IOT-iota004 IOTA_JSON with HTTP binding to CB through IOTA.SC_1 Simple measure received thought IOTA_JSON and HTTP binding -- @1.3 2 min 21 sec 3
>>> features.TS02_iotaflows.004_iotajsonhttp2cb.IOT-iota004 IOTA_JSON with HTTP binding to CB through …
```

revert check_ngsi2 function

---

package.json

Trivial change to `package.json` - adding ` --color true` enables the GitHub Action to display colorfully.

Add  colorization parameter to test

---

lib/commonConfig.js

Related https://github.com/telefonicaid/iotagent-node-lib/issues/963
`checkNgsi2()` is superceded by `isCurrentNgsi()` which in turn can be removed once NGSI-v1 backwards compatibility is dropped in the IoT Agents

Remove checkNgsi2 after compatibility fixes

---

doc/northboundinteractions.md

The North Port interaction documentation was seriously out of date.
This PR switches NGSI-v1 requests for NGSI-v2 equivalents and introduces some NGSI-LD payloads.
NGSI-LD explanation of lazy attributes and Commands has **not** been included as this is still subject to amendment up the ETSI CIM committee.

Remove NGSI-v1 requests and responses

---

CHANGES_NEXT_RELEASE
lib/services/northBound/deviceProvisioningServer.js

Currently a GET device does not retrieve apikey if was provisioned at device level
This PR returns apikey with device provisioning data if was provisioned.
issue https://github.com/telefonicaid/iotagent-node-lib/issues/977

add device.apikey to provisioningAPITranslation

---

CHANGES_NEXT_RELEASE
lib/services/devices/deviceRegistryMongoDB.js

SInce latest iotagent and node-lib verison (from master), when a device with a command is updated a new registrationId is performed (deleting previous one) but no registrationId is properly stored. 
This bug is not reproduced with iotagent 1.16.0 which uses iota-node-lib 2.14.0

 ensure registrationId is updated when a device with commans is updated

---

CHANGES_NEXT_RELEASE
doc/advanced-topics.md
lib/services/devices/registrationUtils.js
lib/services/ngsi/entities-NGSI-LD.js
test/unit/ngsi-ld/examples/contextRequests/updateContextStaticAttributesMetadata.json
test/unit/ngsi-ld/examples/contextRequests/updateContextStaticLinkedAttributes.json
test/unit/ngsi-ld/ngsiService/active-devices-test.js

The whole point of **NGSI-LD** is to be able to traverse the nodes of the knowledge graph. At the moment the IoT Agents just update a single **Device** entity. It is possible to provision relationships in static attributes, but the relationship is directional.
This PR adds the option to update both entities of a relationship  when a measure arrives at the IoT Agent.
`static_attributes` may be supplied with an additional `link` data element when provisioning an IoT Agent to ensure that active attributes from the provisioned IoT Device may be maintained in parallel with a linked data entity . Take for example a temperature gauge placed within a building. The **Device** data model literally represents the IoT device itself, but the `temperature` attribute also needs to be shared with the …

Add linked data entities.

---

.github/workflows/ci.yml
CHANGES_NEXT_RELEASE
doc/deprecated.md
package.json

With the release of 2.15.0, Node 10 can be fully removed for the next release. No rush to merge this, just raising it whilst I remember to do it.

Fully Remove Node 10

---

doc/Contribution.md

FIxed FIWARE Contribution requirements link on Contribution.md file
Old link: https://forge.fiware.org/plugins/mediawiki/wiki/fiware/index.php/Developer_Guidelines
New link: https://fiware-requirements.readthedocs.io/en/latest/

Fix FIWARE Contribution requirements link

---

CHANGES_NEXT_RELEASE
lib/services/devices/deviceRegistryMongoDB.js
lib/services/groups/groupRegistryMongoDB.js

As the mongoose docs state:
> Lean is great for high-performance, read-only cases,

Update MongoDB to use lean()

---

CHANGES_NEXT_RELEASE
doc/advanced-topics.md
lib/services/ngsi/entities-NGSI-v2.js
test/unit/ngsiv2/examples/contextRequests/createBidirectionalDevice.json
test/unit/ngsiv2/examples/contextRequests/createGeopointProvisionedDevice.json
test/unit/ngsiv2/examples/contextRequests/updateContextStaticAttributes.json
test/unit/ngsiv2/ngsiService/geoproperties-test.js

exclude to be translated to geo:json the following types:
geoproperty, point, geo:point, linestring, geo:linestring, polygon, geo:polygon, multipoint, geo:multipoint, multilinestring, geo:multilinestring, multipolygon, geo:multipolygon
keeping their previous type and ensuring backward compatibility with current integrations
hotfix https://github.com/telefonicaid/iotagent-node-lib/issues/1012

type point (and others) should not translated to geo:json

---

CHANGES_NEXT_RELEASE
lib/services/devices/deviceService.js
lib/services/groups/groupRegistryMemory.js
lib/services/groups/groupRegistryMongoDB.js

Fix for https://github.com/telefonicaid/iotagent-node-lib/issues/1011
Search by `apikey` should be enough since `apikey` is unique key in Group model. Ensure that also type match is not necessary.

fix group command in device when entity_type is not equal group entity_type

---

CHANGES_NEXT_RELEASE
lib/services/groups/groupRegistryMemory.js
lib/services/groups/groupRegistryMongoDB.js
lib/services/northBound/restUtils.js

fix for https://github.com/telefonicaid/iotagent-node-lib/issues/1003#issuecomment-815630818
time=2021-04-09T07:49:27.026Z | lvl=DEBUG | corr=46eb979e-c1d1-44de-93cb-d913b841a22b | trans=46eb979e-c1d1-44de-93cb-d913b841a22b | op=IoTAgentNGSI.GenericMiddlewares | from=n/a | srv=smartcity | subsrv=/ | msg=Request for path [/iot/devices] from [localhost:18082] | comp=IoTAgent
time=2021-04-09T07:49:27.026Z | lvl=DEBUG | corr=46eb979e-c1d1-44de-93cb-d913b841a22b | trans=46eb979e-c1d1-44de-93cb-d913b841a22b | op=IoTAgentNGSI.GenericMiddlewares | from=n/a | srv=smartcity | subsrv=/ | msg=Body:
{
"devices": [
{
"device_id": "sensor002",
"entity_name": "sensor002_entity",
"entity_type": "Sensor",
"timezone": "Europe/Berlin",
"attributes": [
{
"object_id": "temperature",
"name": "temperature", …

[WIP] fix error log when get group from type registering a device

---

docker/Mosquitto/Dockerfile
docker/Mosquitto/startMosquitto.sh

Esta Pr hace opcional la creación/edición de los ficheros de configuración dentro del entrypoint. Esto es por que en algunos casos se puede requerir inyectar con un fichero directamente la configuración o x numero de usuarios propios.

update configmap and entrypoint

---

CHANGES_NEXT_RELEASE
lib/services/common/domain.js

time=2021-05-04T11:25:36.533Z | lvl=FATAL | corr=n/a | trans=n/a | op=IoTAgentNG
SI.Global | from=n/a | srv=n/a | subsrv=n/a | msg=An unexpected exception has be
en raised. Ignoring: TypeError: Cannot read property 'service' of undefined
at fillService (/opt/iotaul/node_modules/iotagent-node-lib/lib/services/comm
on/domain.js:198:14)
at saveHandler (/opt/iotaul/node_modules/iotagent-node-lib/lib/services/devi
ces/deviceRegistryMongoDB.js:72:26)
at /opt/iotaul/node_modules/mongoose/lib/model.js:4598:16
at /opt/iotaul/node_modules/mongoose/lib/utils.js:256:11
at /opt/iotaul/node_modules/mongoose/lib/model.js:468:16
at /opt/iotaul/node_modules/kareem/index.js:246:48
at next (/opt/iotaul/node_modules/kareem/index.js:167:27)
at next (/opt/iotaul/node_modules/kareem/index.js:169:9)
at …

check data in fillService facility

---

CHANGES_NEXT_RELEASE
lib/services/ngsi/entities-NGSI-v2.js

time=2021-05-25T09:59:34.816Z | lvl=DEBUG | corr=9a35a73c-3e57-4932-b5b3-b6e059ce4272 | trans=9a35a73c-3e57-4932-b5b3-b6e059ce4272 | op=IoTAgentNGSI.Entities-v2 | from=n/a | srv=smartcity | subsrv=/aa | msg=Updating device value in the Context Broker at [http://iot-orion:1026/v2/entities/thing:disp7/attrs?type=thing] | comp=IoTAgent
time=2021-05-25T09:59:34.816Z | lvl=DEBUG | corr=9a35a73c-3e57-4932-b5b3-b6e059ce4272 | trans=9a35a73c-3e57-4932-b5b3-b6e059ce4272 | op=IoTAgentNGSI.Entities-v2 | from=n/a | srv=smartcity | subsrv=/aa | msg=Using the following NGSI v2 request:
{
"url": "http://iot-orion:1026/v2/entities/thing:disp7/attrs?type=thing",
"method": "POST",
"headers": {
"fiware-service": "smartcity",
"fiware-servicepath": "/aa"
},
"json": {}
}
time=2021-05-25T10:08:35.835Z | …

prevent to update an entity v2 with an empty payload

---

lib/services/ngsi/entities-NGSI-v1.js
lib/services/ngsi/entities-NGSI-v2.js
lib/services/ngsi/ngsiUtils.js

fiware-iot-agent |  | comp=IoTAgent
fiware-iot-agent | time=2021-05-27T07:57:21.337Z | lvl=ERROR | corr=a7bd07b1-cecc-40a5-9412-16477e68d5bd | trans=a7bd07b1-cecc-40a5-9412-16477e68d5bd | op=IoTAgentNGSI.Entities-v2 | from=n/a | srv=tests | subsrv=/ | msg=Operation update error connecting to the Context Broker: {"error":"NotFound","description":"The entity does not have such an attribute"} | comp=IoTAgent
fiware-iot-agent | time=2021-05-27T07:57:21.344Z | lvl=ERROR | corr=a7bd07b1-cecc-40a5-9412-16477e68d5bd | trans=a7bd07b1-cecc-40a5-9412-16477e68d5bd | op=IoTAgentNGSI.DomainControl | from=n/a | srv=tests | subsrv=/ | msg=TypeError: Cannot read property 'details' of undefined
fiware-iot-agent |     at Request._callback (/opt/iotagent-json/node_modules/iotagent-node-lib/lib/services/ngsi/e …

check access to errorField

---

doc/expressionLanguage.md

Fix the example where attributes in the expression miss the `@` and remove the `cast` parameter in the provision as it returns an error 400:
```
{
"name": "WRONG_SYNTAX",
"message": "Wrong syntax in request: Errors found validating request."
}
```
It seems to be an old parameter, it is not described in the documentation, and the cast function it is provided by default using the provide "type" parameter

fix typo in the example of expression legacy

---

doc/advanced-topics.md

Fix typo in the expression of the attributes that miss `@` as prefix.
Add a note about using `IOTA_AUTOCAST=false` to make the example works in the reverse side which expect the attribute as geo:point and no geo:json that is converted with `AUTOCAST=true` by default.

Fix typo in bidirectional example documentation

---

.github/workflows/ci.yml

Upstream fix for telefonicaid/iotagent-node-lib#1021
Uses https://github.com/peter-evans/repository-dispatch - you'll need to set up an organization-wide PAT as described below:
| Name | Description | Default |
| --- | --- | --- |
| `token` | (**required**) A `repo` scoped GitHub [Personal Access Token](https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token). See [token](#token) for further details. | |
Fully working example can be seen here: https://github.com/jason-fox/iotagent-node-lib/actions/runs/1232752364 - this triggered the following Sigfox test run: https://github.com/jason-fox/sigfox-iotagent/actions/runs/1232769234
Eventually this should be expanded to inform other organizations - for example https://github.com/FIWARE/iotagent-isoxml would …

Fix #1021 - Add repository dispatch

---

CHANGES_NEXT_RELEASE
lib/services/ngsi/entities-NGSI-LD.js

Related https://github.com/telefonicaid/fiware-orion/issues/3550
NGSI-LD brokers do not have the same limitation on forbidden characters, but it makes sense to align the NGSI-v2 provisioning keywords `Text` and `TextUnrestricted` to map directly to NGSI-LD `Property` in the same manner as `String` already does.
```console
curl -iX POST \
'http://localhost:4041/iot/services' \                                     
-H 'Content-Type: application/json' \
-H 'fiware-service: openiot' \         
-H 'fiware-servicepath: /' \
-d '{
"services": [
{
"apikey":      "4jggokgpepnvsb2uv4s40d59ov",
"cbroker":     "http://orion:1026",
"entity_type": "Thing",
"resource":    "/iot/json"
}
]
}'
```
```console
curl -iX POST \                    
'http://localhost:4041/iot/devices' \ …
```

Add Text and TextRestricted cases.

---

lib/plugins/multiEntity.js

The improvement was introduced in https://github.com/telefonicaid/iotagent-node-lib/pull/1128/commits/875e46c1069c1d206d5d958d880177a8fdf692b1
But in order keep entity in an array of entties iotagent-json and iotagent-ul tests cases (so many) should be updated.

revert simplification of entities

---

doc/advanced-topics.md
doc/expressionLanguage.md
lib/services/ngsi/entities-NGSI-v2.js

Updates the documentation to explicitly include  GeoJSON examples. This means that examples for the following options are now available:
-  NGSI-LD with legacy - (which still relies on the current conversion function used in NGSI-LD)
-  NGSI-LD with JEXL 
-  NGSI-v2 with JEXL  
Related #1150 , supersedes  #1020

Expand descriptions of GeoJSON.

---

CHANGES_NEXT_RELEASE
doc/usermanual.md
lib/request-shim.js
lib/services/devices/registrationUtils.js
lib/services/ngsi/entities-NGSI-LD.js
lib/services/ngsi/entities-NGSI-v2.js
test/unit/ngsi-ld/lazyAndCommands/lazy-devices-test.js

Since delete regisration has no body
(with latest iota-ul)
time=2022-01-14T10:51:29.231Z | lvl=DEBUG | corr=10fec9c1-ca32-4311-a0c6-9331112fb416 | trans=10fec9c1-ca32-4311-a0c6-9331112fb416 | op=IoTAgentNGSI.Request | from=n/a | srv=iota0030103 | subsrv=/ | msg=Options: {
"url": "http://iot-orion:1026/v2/registrations/61e155adc7ddee5d5a405971",
"method": "DELETE",
"json": true,
"headers": {
"fiware-service": "iota0030103",
"fiware-servicepath": "/"
}
} | comp=IoTAgent
time=2022-01-14T10:51:29.236Z | lvl=DEBUG | corr=10fec9c1-ca32-4311-a0c6-9331112fb416 | trans=10fec9c1-ca32-4311-a0c6-9331112fb416 | op=IoTAgentNGSI.Request | from=n/a | srv=iota0030103 | subsrv=/ | msg=Response {
"orionError": {
"code": "501",
"reasonPhrase": "Not Implemented",
"details": "Request Treat function not …

fix: do not provide context-type for DELETE and GET http requests

---

CHANGES_NEXT_RELEASE
lib/services/ngsi/entities-NGSI-LD.js
lib/services/northBound/contextServer-NGSI-LD.js

NGSI-LD Command query is  returning  attributes in NGSI-v2 format
See: https://github.com/FIWARE/context.Orion-LD/issues/919#issuecomment-1025308901
```json
{
"on": {
"type": "command",
"value": ""
},
"off": {
"type": "command",
"value": ""
}
}
```
```json
{
"on": {
"type": "Property",
"value": {
"@type": "command",
"@value": ""
}
},
"off": {
"type": "Property",
"value": {
"@type": "command",
"@value": ""
}
}
}
```

BugFix: NGSI-LD commands are invalid.

---

CHANGES_NEXT_RELEASE
lib/services/common/domain.js

cleanDomain is called by requestDomain which is called by northbound of iotagents and iotagent-manager
issue https://github.com/telefonicaid/iotagent-node-lib/issues/1201
Similar was done in pep:
https://github.com/telefonicaid/fiware-pep-steelskin/blob/0c7bb57a1f2cf3a22e92d9d94e7298af4870f68a/lib/middleware/domain.js#L73-L87

clean service and subservice when cleanDomain

---

CHANGES_NEXT_RELEASE
doc/northboundinteractions.md
doc/usermanual.md
lib/plugins/expressionPlugin.js
lib/services/ngsi/ngsiService.js

Due to some expressions of attributes could not be executed in a non measure context (i.e. command response from a device), resulting in errors or filling nulls in attrs
This PRs enables commands of devices with another attributes using expressions could transit to PENDING and DELIVERED status

Exclude processing all attrs expression when current attr to update is of type commandStatus of commandResult

---

CHANGES_NEXT_RELEASE
package.json

A vulnerability exists in Async through 3.2.1 for 3.x and through 2.6.3 for 2.x (fixed in 3.2.2 and 2.6.4), which could let a malicious user obtain privileges via the mapValues() method.

upgrade async dep from 2.6.2 version to 2.6.4 due to security vulnerability (CWE-1321)

---

CHANGES_NEXT_RELEASE
lib/services/ngsi/ngsiService.js

Probably fixes:
time=2022-05-12T06:04:16.927Z | lvl=ERROR | corr=n/a | trans=n/a | op=IoTAgentNGSI.Alarms | from=n/a | srv=n/a | subsrv=n/a | msg=Raising [MONGO-ALARM]: {"name":"DEVICE_GROUP_NOT_FOUND","message":"Couldn\t find device group for fields: [\"service\",\"subservice\",\"type\",\"apikey\"] and values: {\"service\":\"sc_vlci\",\"subservice\":\"/medioambiente_emt\",\"type\":\"Device\"}","code":404} | comp=IoTAgent

replace findType by findTypeSilently to avoid raise mongo alarm (DEVICE_GROUP_NOT_FOUND) before launch op against CB 

---

CHANGES_NEXT_RELEASE
lib/services/northBound/contextServerUtils.js

req.headers only contains lowercased headers.
Calling req.headers["NGSILD-Tenant"] will always return undefined. The lib cannot have the expected comportement.
Replacing key with "ngsild-tenant" is fixing the problem. I tested it with iot-agent-json lib ( custom image wiikip/iot-agent-json )

fix: Lower case headers for NGSILD Tenant and NGSILD Path

---

CHANGES_NEXT_RELEASE
lib/services/northBound/contextServer-NGSI-LD.js
test/unit/ngsi-ld/lazyAndCommands/command-test.js

If you look at the latest [NGSI-LD_DRAFT specification](https://docbox.etsi.org/ISG/CIM/Open/drafts/ETSI_GS_CIM-0009_NGSI-LD_DRAFT-for-PUBLIC-COMMENT-V1.5.3.pdf) you will notice there are additional PATCH and PUT endpoints defined
These additional endpoints will become standard across NGSI-LD brokers.
As far as IoT Agents are concerned, for commands, the  new **PUT** `/ngsi-ld/v1/entities/<entity-id>/attrs/<attr-name>` endpoint should be treated the same way as the existing **PATCH**  `/ngsi-ld/v1/entities/<entity-id>/attrs/<attr-name>`  endpoint.
- New **PUT** route is serviced
- Additional Unit test.

Add NGSI-LD 1.6.1 PUT support

---

CHANGES_NEXT_RELEASE
lib/services/northBound/contextServer-NGSI-LD.js
test/unit/ngsi-ld/examples/contextAvailabilityRequests/registerIoTAgentCommands.json
test/unit/ngsi-ld/lazyAndCommands/command-test.js

Extend the existing NGSI-LD support to more of the actuation endpoints defined in the 1.5.3 spec.
-  PUT '/ngsi-ld/v1/entities/:entity/attrs'  🆕 
-  PUT '/ngsi-ld/v1/entities/:entity/attrs/:attr'
- PATCH '/ngsi-ld/v1/entities/:entity/attrs' 🆕 
- PATCH '/ngsi-ld/v1/entities/:entity/attrs/:attr'

Support additional NGSI-LD endpoints

---

CHANGES_NEXT_RELEASE
doc/advanced-topics.md
lib/services/ngsi/entities-NGSI-LD.js
test/unit/ngsi-ld/examples/contextRequests/updateContextLanguageProperties1.json
test/unit/ngsi-ld/ngsiService/languageProperties-test.js

`LanguageProperty` has been defined in the NGSI-LD spec since 1.4.1. This PR correctly maps LanguageProperty to a `languageMap` attribute which is defined in the core `@context` as a JSON-LD `@container: @lang`. 
`LanguageProperty` is most likely to be a static attribute, but active measures can also be supported - it is basically the same idea as mapping `Relationship` and the `object` attribute.
- Update Docs
- Update Unit Test
- Add `LanguageProperty` exception clause to `switch`

Add NGSI-LD LanguageProperty support

---

CHANGES_NEXT_RELEASE
lib/services/northBound/contextServer-NGSI-LD.js
test/unit/ngsi-ld/lazyAndCommands/command-test.js

In NGSI-LD, normally `http://{{iot-agent}}/ngsi-ld/v1/entities/<entity-id>` will return lazy attributes , however, I just noticed a bug related to commands. If a device had registered commands, but no registered lazy attribute it was failing with a null pointer and the response was not valid:
- Defensive Programming - add null check to attributes
- Add Test.
`http://{{iot-agent}}/ngsi-ld/v1/entities/<entity-id>` is one of the **valid** NGSI-LD endpoints defined in the 1.5.3 spec which the IoT Agent should service. 
Admittedly, ideally the context broker **shouldn't** need to call the IoT Agent at all in this case (with commands but no lazy attributes) but since  is a valid request when a device has lazy attributes or when a device has lazy attributes **and** commands, it shouldn't error …

Ensure GET `http://{{iot-agent}}/ngsi-ld/v1/entities/<entity-id>` returns a valid response

---

CHANGES_NEXT_RELEASE
lib/errors.js
lib/services/northBound/contextServer-NGSI-LD.js
test/unit/ngsi-ld/ngsiService/unsupported-endpoints-test.js

-  GET `/ngsi-ld/v1/entities`
-  POST `/ngsi-ld/v1/entities`
-  DELETE `/ngsi-ld/v1/entities/<entity-id>`
-  DELETE `ngsi-ld/v1/entities/<entity-id>/attrs/<attr-name>`
Are valid NGSI-LD endpoints, but IoT Agents will never support them. Ensure that they return valid NGSI-LD error responses instead. This protects the IoT Agent and also informs the Context Broker of the reason why. For example, at the moment Scorpio assumes full federated `/ngsi-ld/v1/entities` is supported when it isn't. see: telefonicaid/iotagent-ul/issues/573

Add NGSI-LD Unsupported Endpoints

---

CHANGES_NEXT_RELEASE
lib/request-shim.js

Use [`util.inspect(error)` ](https://nodejs.org/api/util.html#utilinspectobject-options) on error messages so that even circular objects are logged correctly.
This is particularly an issue when running the unit tests as the debug message `Converting circular structure to JSON` is useless when reading the request. Adding this in means that you get meaningful errors back from should.js e.g:
```text
msg=An unexpected exception has been raised. Ignoring: Error [AssertionError]: expected false to be true
at Assertion.fail (node_modules/should/cjs/should.js:275:17)
at Assertion.value (node_modules/should/cjs/should.js:356:19)
at ../iotagent-node-lib/test/unit/ngsi-ld/plugins/bidirectional-plugin_test.js:318:44
at ../iotagent-node-lib/lib/request-shim.js:64:716
at processTicksAndRejections …
```

Avoiding  Converting circular structure to JSON error in log

---

CHANGES_NEXT_RELEASE
lib/plugins/bidirectionalData.js
lib/plugins/expressionPlugin.js

Related: https://github.com/telefonicaid/iotagent-node-lib/pull/1266#issuecomment-1217786005
This would remove the hardcoded `legacyParser` from the Bidirectionality plugin.

Update Bidirectional plugin to use expressionPlugin

---

doc/apiary/iotagent.apib
doc/expressionLanguage.md
doc/getting-started.md
examples/TTOpen-service.json
lib/templates/deviceGroup.json
test/unit/examples/mongoCollections/configurations.json
test/unit/ngsi-mixed/provisioning/ngsi-versioning-test.js
test/unit/ngsiv2/provisioning/device-provisioning-api_test.js

This PR intends to replace all occurrences of `cbroker` on the examples, documentation and tests. This can lead to misunderstanding since this field actually does not have any functionality. The right parameter is [`cbHost`](https://github.com/telefonicaid/iotagent-node-lib/search?q=cbhost)

Replace all `cbroker` references in codebase

---

doc/deprecated.md

Related #1302 - You should provide a heads up that the supported NGSI-LD interface will no longer accept the 1.3.1 `property` attribute in the `CSourceRegistration` at some point. This is just preparatory work before that PR can land at some time in the future.

Add deprecation notice

---

doc/advanced-topics.md

A new section added after issue #1301 in order to clarify how the different config params interacts.

Add new doc section explaining `autoprovision`, `explicitAttrs` and `appendMode`

---

CHANGES_NEXT_RELEASE
doc/deprecated.md
lib/services/devices/registrationUtils.js
test/unit/ngsi-ld/examples/contextAvailabilityRequests/registerIoTAgent1.json
test/unit/ngsi-ld/examples/contextAvailabilityRequests/registerIoTAgent2.json
test/unit/ngsi-ld/examples/contextAvailabilityRequests/registerIoTAgent4.json
test/unit/ngsi-ld/examples/contextAvailabilityRequests/registerIoTAgentCommands.json
test/unit/ngsi-ld/examples/contextAvailabilityRequests/registerProvisionedDevice.json
test/unit/ngsi-ld/examples/contextAvailabilityRequests/registerProvisionedDevice2.json
test/unit/ngsi-ld/examples/contextAvailabilityRequests/registerProvisionedDeviceWithGroup.json
test/unit/ngsi-ld/examples/contextAvailabilityRequests/registerProvisionedDeviceWithGroup2.json
test/unit/ngsi-ld/examples/contextAvailabilityRequests/registerProvisionedDeviceWithGroup3.json
test/unit/ngsi-ld/examples/contextAvailabilityRequests/updateCommands1.json
test/unit/ngsi-ld/examples/contextAvailabilityRequests/updateIoTAgent1.json
test/unit/ngsi-ld/examples/contextAvailabilityRequests/updateIoTAgent2.json

Related to https://github.com/telefonicaid/iotagent-ul/issues/573#issuecomment-1203172196
The [NGSI-LD 1.6.1 Specification](https://www.etsi.org/deliver/etsi_gs/CIM/001_099/009/01.06.01_60/gs_CIM009v010601p.pdf), clarifies the definition of registrations and defines `operations` and `mode` attributes to be supplied within NGSI-LD **CSourceRegistrations**.  A default Registration is considered to be `federationOps/inclusive` (which is what [Scorpio 3](https://github.com/ScorpioBroker/ScorpioBroker/releases) already offers and [Orion-LD 1.2](https://github.com/FIWARE/context.Orion-LD/releases) is aiming for.
This is a potentially **breaking change** for provisioning NGSI-LD devices - the existing functionality  aligns with the Orion-LD 1.1 prototype only - there is little point in …

Update to offer NGSI-LD 1.6.1. Registration

---

doc/deprecated.md

Should other parts of the doc edited? 
I.E:
https://github.com/telefonicaid/iotagent-ul/blob/b7e3099e3eb08dc03f45f1f2d5595f6381326971/docker/README.md?plain=1#L19-L27

Add `deviceRegistry.type=memory` deprecation message

---

CHANGES_NEXT_RELEASE
lib/services/ngsi/entities-NGSI-v2.js
test/unit/ngsiv2/examples/contextRequests/updateContextExpressionPlugin40.json
test/unit/ngsiv2/expressions/jexlBasedTransformations-test.js

Add to context for explictAttrs jexl evaluation the following missed concepts:
- active attributes with expressions (and also indentified by its object_id)
- Measures identified by its object_id)
Check if explicitAttr list contains attributes identified by its object_id

add to ctxt all active attrs for explicitAttrs when is a jexl

---

CHANGES_NEXT_RELEASE
lib/services/ngsi/entities-NGSI-v2.js
test/unit/ngsiv2/examples/contextRequests/updateContextExpressionPlugin41.json
test/unit/ngsiv2/examples/contextRequests/updateContextMultientityPlugin25.json
test/unit/ngsiv2/expressions/jexlBasedTransformations-test.js
test/unit/ngsiv2/plugins/multientity-plugin_test.js

Fix/explicit attributes true: just measures in active attrs and active attrs with expressions

---

lib/services/ngsi/entities-NGSI-v2.js
test/unit/ngsiv2/examples/contextRequests/updateContextExpressionPlugin35.json
test/unit/ngsiv2/examples/contextRequests/updateContextExpressionPlugin41.json
test/unit/ngsiv2/expressions/jexlBasedTransformations-test.js

Continuation of PR https://github.com/telefonicaid/iotagent-node-lib/pull/1355
Adds TimeInstant as is expected by https://github.com/telefonicaid/iotagent-node-lib/blob/master/doc/advanced-topics.md#explicitly-defined-attributes-explicitattrs
Case 2:
"explicitAttrs": true
just measures defined in active, static (plus conditionally TimeInstant) will be propagated to NGSI interface.
Allow refer to measure by attr name or attr object_id

add timeinstant to explicitAttrs true case

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/advanced-issue-labeler.yml
.github/workflows/issue-labeler.yml
.github/workflows/issue-labelert.yml

This PR add issue template to the repo. 
2 templates added:
- Bug report
- Feature request
Additionally, a GH action - [Advanced Issue Labeler](https://github.com/marketplace/actions/advanced-issue-labeler) -  is included, in order to label issues according to the options choose under dropdown selectors in templates.
This issue labeler assigns, for each type of issues:
**Bug report**
NGSI Version. Possible values:
- NGSIv2
- NGSI-LD
**Feature request**
Type. Possible values:
- New feature
- Enhancement
- Techdeb

Add Issue template

---

CHANGES_NEXT_RELEASE
lib/templates/updateDevice.json
lib/templates/updateDeviceLax.json

Templating stuff are preventing of update (via device API)  some fields of devices as timestamp
time=2023-06-27T08:51:51.354Z | lvl=DEBUG | corr=a40fa76d-fdfd-486c-b08d-67587e2f8ef0 | trans=4f8350e7-3d70-400a-9d4c-94ecabfb9443 | op=IoTAgentNGSI.GenericMiddlewares | from=172.17.0.21 | srv=smartcity | subsrv=/ | msg=Body:
{
"entity_type": "thing",
"static_attributes": [],
"commands": [],
"apikey": "7xbfgqg25bz0ersloin9gqd7h",
"explicitAttrs": false,
"timestamp": true,
"expressionLanguage": "jexl"
}
| comp=IoTAgent
time=2023-06-27T08:51:51.354Z | lvl=DEBUG | corr=a40fa76d-fdfd-486c-b08d-67587e2f8ef0 | trans=4f8350e7-3d70-400a-9d4c-94ecabfb9443 | op=IoTAgentNGSI.RestUtils | from=172.17.0.21 | srv=smartcity | subsrv=/ | msg=Errors found validating request: …

 allow update timestamp and other config fields of device

---

CHANGES_NEXT_RELEASE
doc/api.md
lib/services/devices/deviceService.js

issue https://github.com/telefonicaid/iotagent-node-lib/issues/1377
This way autorpovisioned devices with remain without some flags defined like timestamp, expressionLanguage (which will take in runtime from group configuration)

Do not propage group config to autoprovision device

---

CHANGES_NEXT_RELEASE
doc/api.md
lib/services/devices/deviceService.js
lib/services/devices/devices-NGSI-v2.js
test/unit/ngsi-ld/lazyAndCommands/merge-patch-test.js
test/unit/ngsiv2/provisioning/device-provisioning-api_test.js

Related with issue https://github.com/telefonicaid/iotagent-node-lib/issues/1377
To avoid duplicate  static, lazy and commands from groups into device
They were added by  https://github.com/telefonicaid/iotagent-node-lib/commit/c7e663c7e375ff616c78a973403a7f340aed05a2

do not include static, lazy and commands in complete registrations

---

lib/services/devices/deviceService.js

Reverts telefonicaid/iotagent-node-lib#1400
explicitAttrs from config only needs be deleted from findorCreate as was done in https://github.com/telefonicaid/iotagent-node-lib/pull/1391
But mergeWithConfig needs that all non defined flags in device were filled with group values

Revert "Update deviceService.js"

---

CHANGES_NEXT_RELEASE
lib/plugins/jexlParser.js

Check access extracting variables in jexlPlugin when bidirectional plugin
Related with https://github.com/telefonicaid/iotagent-node-lib/pull/1361/
time=2023-07-06T10:14:45.871Z | lvl=DEBUG | corr=1a11c061-2335-4a66-9e3f-682f83307bfe | trans=205a2746-78a2-481f-8dce-bd9881e52010 | op=IoTAgentNGSI.GenericMiddlewares | from=172.17.0.1 | srv=fi014 | subsrv=/ssfi014sc01 | msg=Body:
{
"devices": [
{
"attributes": [
{
"expression": "\" + latitude + \",\" + longitude + \"",
"type": "percent",
"name": "location",
"object_id": "location",
"reverse": [
{
"expression": "location | substr(location | indexOf(',') + 1, location | length) | trim",
"type": "string",
"object_id": "longitude"
},
{
"expression": " location | substr(0, location | indexOf(',')) | trim",
"type": "string",
"object_id": …

check array access in jexlPlugin when bidirectionalPlugin (extractVariables)

---

CHANGES_NEXT_RELEASE
lib/model/dbConn.js

Currently, the full MongoDB connection **options** object is displayed at INFO level in logs. This **options** object contains the db credentials, so the log exposes those credentials. I think it's better to remove the **options** object from logs (the host and port are kept).

Remove MongoDB connection options from log, to avoid credentials display

---

CHANGES_NEXT_RELEASE
lib/services/devices/deviceService.js
test/unit/general/contextBrokerKeystoneSecurityAccess-test.js
test/unit/ngsiv2/general/contextBrokerOAuthSecurityAccess-test.js
test/unit/ngsiv2/general/https-support-test.js
test/unit/ngsiv2/lazyAndCommands/command-test.js
test/unit/ngsiv2/lazyAndCommands/polling-commands-test.js
test/unit/ngsiv2/ngsiService/subscriptions-test.js
test/unit/ngsiv2/plugins/bidirectional-plugin_test.js
test/unit/ngsiv2/provisioning/device-provisioning-api_test.js
test/unit/ngsiv2/provisioning/device-registration_test.js
test/unit/ngsiv2/provisioning/device-update-registration_test.js
test/unit/ngsiv2/provisioning/singleConfigurationMode-test.js
test/unit/ngsiv2/provisioning/updateProvisionedDevices-test.js
test/unit/plugins/capture-provision-inPlugins_test.js

Initial entity was created when a new device is created or just a measure for a new unprovisioned device comes.
In both cases  a new entity (with some  attrs with null values) is created.
Needs https://github.com/telefonicaid/iotagent-node-lib/pull/1111

do not create initial entity

---

CHANGES_NEXT_RELEASE
lib/fiware-iotagent-lib.js
lib/services/commands/commandService.js
lib/services/common/genericMiddleware.js
lib/services/devices/deviceRegistryMemory.js
lib/services/devices/deviceRegistryMongoDB.js
lib/services/devices/deviceService.js
lib/services/devices/devices-NGSI-LD.js
lib/services/devices/devices-NGSI-v2.js
lib/services/groups/groupService.js
lib/services/northBound/deviceProvisioningServer.js
test/unit/general/contextBrokerKeystoneSecurityAccess-test.js
test/unit/mongodb/mongodb-registry-test.js
test/unit/ngsi-ld/general/contextBrokerOAuthSecurityAccess-test.js
test/unit/ngsi-ld/general/https-support-test.js
test/unit/ngsi-ld/ngsiService/subscriptions-test.js
test/unit/ngsi-ld/provisioning/device-registration_test.js
test/unit/ngsi-ld/provisioning/device-update-registration_test.js
test/unit/ngsiv2/general/contextBrokerOAuthSecurityAccess-test.js
test/unit/ngsiv2/general/https-support-test.js
test/unit/ngsiv2/ngsiService/subscriptions-test.js
test/unit/ngsiv2/provisioning/device-registration_test.js
test/unit/ngsiv2/provisioning/device-update-registration_test.js

Based on 
https://github.com/telefonicaid/iotagent-node-lib/pull/1427
issue 
https://github.com/telefonicaid/iotagent-node-lib/issues/1435
issue https://github.com/telefonicaid/iotagent-node-lib/issues/1426
Type of group and device could be different (specially when device is provisioned explicitly)
This fix implies that all provisioned devices has a valid apikey

Task/use apikey to find, update and remove device

---

README.md
doc/admin.md
doc/api.md
doc/devel/development.md
doc/devel/northboundinteractions.md
doc/index.md

Review the whole documentation in order to remove deprecated / removed features

---

doc/deprecated.md

Related PR https://github.com/telefonicaid/iotagent-node-lib/pull/1437

FIX deprecated.md

---

lib/services/devices/devices-NGSI-LD.js
lib/services/devices/devices-NGSI-mixed.js

Static analysis of the changes between 3.3.0 and 3.4.0 indicates that the `createInitialEntity` from NGSI-v2. This PR does the same for "LD "and "mixed". There is no change in the tests, but coverage should increase marginally

Remove lava code

---

CHANGES_NEXT_RELEASE
doc/api.md
lib/services/ngsi/entities-NGSI-v2.js
package.json
test/unit/ngsiv2/ngsiService/active-devices-test.js

Issue https://github.com/telefonicaid/iotagent-node-lib/issues/1485
this should be tested

FIX: Remove measures with attributes name 'id' or 'type' (hotfix 3.4.3)

---

CHANGES_NEXT_RELEASE
lib/plugins/jexlParser.js

Log about "Wrong expression found .... over " is produced by contextAvailable of jexl plugin:
from https://github.com/telefonicaid/iotagent-node-lib/commit/d29e0060198355fde96153f31c5e7c8cdcf1d5f8

Change log level from warn to info contextAvailable exception

---

CHANGES_NEXT_RELEASE
lib/services/devices/deviceService.js
test/unit/ngsiv2/provisioning/device-provisioning-api_test.js

typeInformation should contain that timestamp=false in an autoprovision of device with a group with timestamp=false
Related with issue https://github.com/telefonicaid/iotagent-node-lib/issues/1504 and the expected new tests about it

fix: autoprovision with group timestamp false

---

lib/plugins/jexlParser.js

After removing the code related to extractVariables function (used by bidirectional plugin) in this PR: https://github.com/telefonicaid/iotagent-node-lib/pull/1495
Those 2 dependencies are not required anymore

Remove unsued dependencies from jexlParser.js

---

CHANGES_NEXT_RELEASE
lib/model/dbConn.js
test/unit/mongodb/mongodb-connectionoptions-test.js

*Edit:* issue #1526 
- Overriding when user:pass is present in extraArgs
- Fix tests
I see that authSource had an independant ENV variable and treatment along the code, but the truth it's that authSource should concat in the string as an extraArgs. 
In my opinion the best way to allow backwards compatibility is to still parsing if comes in extraArgs, but overriding if the specific env variable is present. 
Also authSource should only used if user:pass are present so i included in the if statemente

[Fix] Parse authSource variable into mongo url string

---

doc/api.md

Add specific case for not provisioned attributes but defined in the `explicitAttrs` array

[Doc] Fix explicitAttrs doc

---

test/functional/testCases.js

Modify tests to skip this cases in JSON agent untill the following issue is fixed:
https://github.com/telefonicaid/iotagent-json/issues/782

Skip explicitAttrs No Lib

---

test/functional/README.md

https://github.com/telefonicaid/iotagent-node-lib/pull/1531#discussion_r1403108895

Update tests/functional/README.md to improve skip doc

---

CHANGES_NEXT_RELEASE
lib/services/devices/deviceService.js
test/functional/testCases.js
test/functional/testUtils.js

Bug introduced in 3.3.0 by https://github.com/telefonicaid/iotagent-node-lib/pull/1396
commands from groups should be stored in device since registration is only possible against device entity.
Otherwise commands is stored in entity as normal string type attribute.
Moreover any command group modification requires device registration would be done again, and then implies device and entity should be deleted previously.

store in device commands from group after CB registration

---

doc/api.md

Fix for https://github.com/telefonicaid/iotagent-node-lib/issues/1555
'FIware-service path /*' is not a feature implemented in iotagent

remove references to fiware-servicepath with wildcards

---

CHANGES_NEXT_RELEASE
doc/api.md
lib/services/northBound/deviceProvisioningServer.js
test/unit/ngsiv2/provisioning/removeProvisionedDevice-test.js

issue https://github.com/telefonicaid/iotagent-node-lib/issues/1578

add multiple delete of devices

---

CHANGES_NEXT_RELEASE
lib/services/ngsi/entities-NGSI-v2.js
lib/services/ngsi/ngsiService.js

typeInformation contain global config values

---

CHANGES_NEXT_RELEASE
lib/errors.js
lib/services/commands/commandRegistryMemory.js
lib/services/commands/commandRegistryMongoDB.js
lib/services/devices/deviceRegistryMemory.js
lib/services/devices/deviceRegistryMongoDB.js
lib/services/devices/deviceService.js
lib/services/devices/devices-NGSI-LD.js
lib/services/devices/devices-NGSI-v2.js
lib/services/groups/groupRegistryMemory.js
lib/services/groups/groupRegistryMongoDB.js
lib/services/groups/groupService.js
lib/services/ngsi/entities-NGSI-LD.js
lib/services/ngsi/entities-NGSI-v2.js
lib/services/ngsi/ngsiService.js
lib/services/ngsi/subscription-NGSI-LD.js
lib/services/ngsi/subscription-NGSI-v2.js
lib/services/northBound/contextServer-NGSI-LD.js
lib/services/northBound/contextServer-NGSI-v2.js
lib/services/northBound/deviceProvisioningServer.js
lib/services/northBound/restUtils.js
test/unit/ngsi-ld/ngsiService/active-devices-test.js

- EntityGenericError 
- BadTimestamp
- TypeNotFound
- DeviceNotFound
- MissingAttributes
- DuplicateDeviceId 
- DuplicateGroup 
- CommandNotFound
- GroupNotFound
- BadGeocoordinates

add device/group information to error log about some errors

---

CHANGES_NEXT_RELEASE

Given that #1598 (issue) has been closed and PR #1601 refers to that issue, I wonder if changelog should be changed in the way this PR does.

FIX reference in CHANGES_NEXT_RELEASE

---

CHANGES_NEXT_RELEASE
doc/api.md
lib/services/ngsi/entities-NGSI-v2.js
test/functional/README.md
test/functional/testCases.js
test/functional/testUtils.js

related to fix https://github.com/telefonicaid/iotagent-json/issues/825

allow to send to CB batch update for multimeasures (and sort them by TimeInstant)

---

CHANGES_NEXT_RELEASE
lib/services/ngsi/entities-NGSI-LD.js

… in update operation
with orion ld 1.5.1 during the transmission of the first measure operation the context broker respond with 201 status code.
The log reports
```
time=2024-05-30T16:55:53.988Z | lvl=DEBUG | corr=01307aed-e06c-4a1f-84b5-2719df05fde3 | trans=01307aed-e06c-4a1f-84b5-2719df05fde3 | op=IoTAgentNGSI.Request | from=n/a | srv=openiot | subsrv=/ | msg=Options: {
"url": "http://orion:1026/ngsi-ld/v1/entityOperations/upsert/?options=update",
"method": "POST",
"headers": {
"fiware-service": "openiot",
"fiware-servicepath": "/",
"Content-Type": "application/ld+json",
"NGSILD-Tenant": "openiot",
"NGSILD-Path": "/"
},
"json": [
{
"@context": "http://context/datamodels.context.jsonld",
"id": "urn:ngsi-ld:HeightSensor:hsensor31061690_a",
"type": "HeightSensor",
"height": {
"type": …
```

[NGSILD] fix ENTITY_GENERIC_ERROR when context broker respond with status code… (201 code)

---

CHANGES_NEXT_RELEASE
doc/api.md
lib/services/ngsi/entities-NGSI-v2.js
test/functional/testCases.js

This is another  suggestion to fix cases proposed in https://github.com/telefonicaid/iotagent-node-lib/pull/1610
having into account this logic This is my suggestion to fix cases proposed in https://github.com/telefonicaid/iotagent-node-lib/pull/1610

Add TimeInstant + explicitAttr tests (func test 533)

---

test/functional/testCases.js

Test for https://github.com/telefonicaid/iotagent-node-lib/issues/1621

add test about usage of object_id attrs with special format name

---

CHANGES_NEXT_RELEASE
lib/services/groups/groupService.js
test/unit/ngsiv2/provisioning/device-group-api-test.js

Fixes #1528. Now, uppercase value can also be used for service header in case of update and delete.

Fix Service Header to use upper case value

---

doc/api.md

Maybe related (not sure) #1634

FIX metadata expression evaluation in doc

---

test/functional/functional-tests-runner.js
test/functional/functional-tests.js
test/functional/testCases.js

fix for https://github.com/telefonicaid/iotagent-node-lib/pull/1523

access to id, service and subservice in jexl context for functional test

---

doc/api.md
lib/services/stats/statsRegistry.js
test/unit/statsRegistry/openmetrics-test.js

Continuation to #1627 - The current version of prometheus collector in openshift has been found to request openmetrics 0.0.1

Add support for openmetrics 0.0.1 besides 1.0.0

---

doc/getting-started.md

This PR modifies getting started document using IoTA JSON and completing the documentation. Commands are pending but probably is not needed in this document
https://github.com/telefonicaid/iotagent-node-lib/issues/1645

Modify getting started to use IoTA JSON

---

CHANGES_NEXT_RELEASE
doc/api.md
doc/deprecated.md
doc/getting-started.md
lib/constants.js
lib/services/northBound/deviceGroupAdministrationServer.js
test/functional/README.md
test/unit/examples/groupProvisioningRequests/multipleConfigGroupsCreation.json
test/unit/examples/groupProvisioningRequests/provisionDuplicateConfigGroup.json
test/unit/examples/groupProvisioningRequests/provisionFullConfigGroup.json
test/unit/examples/groupProvisioningRequests/provisionFullConfigGroupAlternate.json
test/unit/general/deviceService-test.js
test/unit/mongodb/mongodb-configGroup-registry-test.js
test/unit/mongodb/mongodb-group-registry-test.js
test/unit/mongodb/mongodb-service-registry-test.js
test/unit/ngsiv2/general/deviceService-test.js
test/unit/ngsiv2/general/iotam-autoregistration-test.js
test/unit/ngsiv2/provisioning/device-group-api-test.js
test/unit/ngsiv2/provisioning/device-provisioning-configGroup-api_test.js

This PR solves #752 
This PR overpasses #1637

Add new `/iot/groups` API route

---

CHANGES_NEXT_RELEASE
package.json

step 4.5.0-next -> 4.6.0

---

CHANGES_NEXT_RELEASE
package.json

https://github.com/telefonicaid/iotagent-node-lib/issues/1658
Curerntly iotagents are using express 4.20 already

Update package.json: express from 4.19 to 4.20

---

doc/api.md

related with #1633 #1589
Given a measure (identified by an apikey) there is no way to identify group related if apikey is not unique for all services and subservices.
My comment https://github.com/telefonicaid/iotagent-node-lib/issues/1633#issuecomment-2272722185 was  taken directly from https://github.com/telefonicaid/iotagent-node-lib/pull/1592#discussion_r1551377609

fix doc uniqueness group

---

CHANGES_NEXT_RELEASE
lib/commonConfig.js
lib/services/devices/deviceService.js

Autoprovisioned devices are not setting polling and transport when are created. When related group has no info about transport nither endpoint then if defaultTransport in agent is HTTP polling true is not defined in autoprovisioned device.
This bug was introduced by https://github.com/telefonicaid/iotagent-json/pull/794

set polling for autoprovisioned devices

---

CHANGES_NEXT_RELEASE
lib/model/Device.js
lib/services/devices/deviceRegistryMongoDB.js
lib/services/devices/deviceService.js

Unique index for Device model + handle duplicated mongo error when device is autoprovisioned.
Issue https://github.com/telefonicaid/iotagent-node-lib/issues/1576
Related with https://github.com/telefonicaid/iotagent-node-lib/blob/master/doc/api.md#uniqueness-of-groups-and-devices
and fixes: https://github.com/telefonicaid/iotagent-json/issues/865

Add unique index for Device model
