.jshintrc
lib/services/deviceProvisioningServer.js
lib/services/ngsiService.js
test/unit/device-registration_test.js
test/unit/mongodb-registry-test.js

The field registrationId in the Device Model was not populated (and is needed by the IOT Agents).

FIX Device registration ID was not populated in the model

---

lib/errors.js
lib/services/ngsiService.js
test/unit/active-devices-test.js

ADD Guard against lack of type in type definitions

---

lib/fiware-iotagent-lib.js
lib/services/contextServer.js
lib/services/northboundServer.js
test/unit/command-test.js
test/unit/device-registration_test.js
test/unit/device-update-registration_test.js
test/unit/lazy-devices-test.js

ADD Command handler to the Context Server

ADD Command Handler to the context server

---

lib/model/Device.js
lib/services/deviceRegistryMongoDB.js
test/unit/contextAvailabilityRequests/registerIoTAgent3.json
test/unit/contextAvailabilityRequests/unregisterDevice3.json
test/unit/mongodb-registry-test.js

FIX Mongo DB repository did not store the Commands

ADD Comands to MongoDB repository

---

lib/services/ngsiService.js

FIX Hardcoded command name

---

lib/errors.js
lib/fiware-iotagent-lib.js
test/unit/startup-test.js

Add configuration checks at the startup.
Fixes #84 
Fixes #83

ADD Configuration checks at startup

---

CHANGES_NEXT_RELEASE

Add missing changes to change list

ADD Changes to change list

---

examples/lwm2m-deviceActiveCustom.json
examples/lwm2m-deviceActiveOMA.json
examples/lwm2m-devicePassiveCustom.json
examples/lwm2m-serviceActiveOMA.json
examples/lwm2m-servicePassiveOMA.json

Add LWM2M provisioning examples.

ADD Examples of provisioning for Lightweight M2M

---

CHANGES_NEXT_RELEASE
lib/services/contextServer.js

Fix a crash detected testing the test tools.

FIX Crash adding static attributes to null vector

---

CHANGES_NEXT_RELEASE
bin/agentConsole.js
lib/fiware-iotagent-lib.js
lib/services/contextServer.js
lib/services/ngsiService.js
package.json
test/unit/contextBrokerSecurityAccess-test.js
test/unit/contextRequests/queryContext1.json
test/unit/contextResponses/queryContext1Success.json
test/unit/queryDeviceInformationInCb-test.js

New minor release adding query functionalities to the library.

Release 0.5.5

---

CHANGES_NEXT_RELEASE
lib/services/ngsiService.js
test/unit/active-devices-test.js

ADD Information to generic transport errors connecting to the CB

---

package.json

Prepare next release

---

lib/services/deviceGroupAdministrationServer.js
lib/services/northboundServer.js
test/unit/device-group-api-test.js
test/unit/iotam-autoregistration-test.js
test/unit/mongodb-group-registry-test.js

FIX URLs to conform to new API

---

LICENSE

ADD LICENCE file to the repository

---

CHANGES_NEXT_RELEASE
lib/services/ngsi/ngsiParser.js
lib/services/northBound/contextServer.js
lib/services/northBound/northboundServer.js
lib/services/northBound/restUtils.js

FIX Use express methods to check mime type

---

lib/templates/updateContext.json

Fixes small problem in validation with new values of the TT Agent

ADD Any type for value in JSON Schema

---

package.json

ADD New release version

---

README.md

Fix typos in the URLs of the Configuration API.

FIX URL for configuration group API

---

CHANGES_NEXT_RELEASE
lib/services/common/iotManagerService.js
lib/services/northBound/deviceProvisioningServer.js
test/unit/iotamRequests/registrationEmpty.json
test/unit/iotamRequests/registrationWithGroups.json
test/unit/listProvisionedDevices-test.js
test/unit/removeProvisionedDevice-test.js

Add /iot prefix for IoTAM integartion.

ADD Prefix /iot to the IoTAgent registration in the IOTAM

---

lib/services/ngsi/ngsiService.js

Fix missing entity in query callback.

FIX missing entity in query callback

---

CHANGES_NEXT_RELEASE
lib/services/northBound/deviceProvisioningServer.js
test/unit/removeProvisionedDevice-test.js

FIX Delete return code

---

CHANGES_NEXT_RELEASE
examples/GDLdevice.json
examples/GDLgroup.json
lib/plugins/compressTimestamp.js
lib/plugins/pluginUtils.js

Refactor the time compression plugin to extract common features

---

CHANGES_NEXT_RELEASE
lib/services/ngsi/ngsiService.js
test/unit/compress-timestamp-plugin_test.js
test/unit/translation-plugin_test.js

FIX Extra parameter in query callback

---

CHANGES_NEXT_RELEASE
README.md

FIX Device provisioning documentation

---

CHANGES_NEXT_RELEASE
lib/plugins/attributeAlias.js
lib/templates/createDevice.json
lib/templates/updateDevice.json
test/unit/alias-plugin_test.js

FIX Appropriate name for attribute ids

---

CHANGES_NEXT_RELEASE
lib/services/northBound/deviceProvisioningServer.js
test/unit/listProvisionedDevices-test.js

FIX Object IDs in get provisioned device

---

CHANGES_NEXT_RELEASE
lib/plugins/attributeAlias.js
lib/services/devices/deviceService.js
lib/services/northBound/deviceProvisioningServer.js
test/unit/device-provisioning-api_test.js

FIX Both object_id and id stored for attributes

---

CHANGES_NEXT_RELEASE
lib/constants.js
lib/plugins/pluginUtils.js
test/unit/active-devices-test.js
test/unit/compress-timestamp-plugin_test.js
test/unit/contextRequests/updateContextCompressTimestamp1.json
test/unit/contextRequests/updateContextCompressTimestamp2.json
test/unit/contextRequests/updateContextTimestamp.json
test/unit/contextRequests/updateContextTimestampOverride.json
test/unit/contextResponses/queryContextCompressTimestamp1Success.json
test/unit/contextResponses/updateContextCompressTimestamp2Success.json

FIX Change timestamp type to 'ISO8601'

---

CHANGES_NEXT_RELEASE
lib/services/groups/groupRegistryMongoDB.js
lib/services/groups/groupService.js

FIX Wrong log entries creating configurations

---

CHANGES_NEXT_RELEASE
README.md
lib/model/Device.js
lib/services/northBound/deviceProvisioningServer.js
test/unit/device-provisioning-api_test.js
test/unit/deviceProvisioningRequests/provisionNewDevice.json
test/unit/statistics-persistence_test.js

Add endpoint attribute to Device Provisioning API and device model.

ADD Endpoint attribute to Device model

---

lib/constants.js
lib/services/devices/deviceService.js
lib/services/ngsi/ngsiService.js
lib/services/northBound/contextServer.js
lib/services/northBound/deviceProvisioningServer.js
lib/templates/createDevice.json
lib/templates/updateDevice.json
test/unit/contextRequests/updateContextCommandError.json
test/unit/contextRequests/updateContextCommandFinish.json
test/unit/contextRequests/updateContextCommandStatus.json
test/unit/contextResponses/updateContextCommandFinishSuccess.json
test/unit/contextResponses/updateContextCommandStatusSuccess.json
test/unit/lazy-devices-test.js
test/unit/statistics-persistence_test.js
test/unit/updateProvisionedDevices-test.js

Fixes errors found in the integration with the IoT Manager.

ADD Changes to integrate with IOTAManager

---

lib/errors.js
test/unit/device-group-api-test.js
test/unit/device-provisioning-api_test.js
test/unit/mongodb-group-registry-test.js

Fix the edit group error codes from 400 to 409.

FIX Group edit error codes

---

.sonar-project.properties
CHANGES_NEXT_RELEASE

ADD Required sonar project files

---

CHANGES_NEXT_RELEASE
lib/services/northBound/contextServer.js

FIX Static attributes in query context

---

CHANGES_NEXT_RELEASE
package.json

FIX Mongodb error

---

CHANGES_NEXT_RELEASE
lib/services/ngsi/ngsiService.js
test/unit/staticAttributes-test.js

FIX Multiple timestamp additions

---

CHANGES_NEXT_RELEASE
lib/command/commandLine.js
lib/services/groups/groupRegistryMongoDB.js
test/unit/mongodb-group-registry-test.js

FIX List error removing configurations

---

CHANGES_NEXT_RELEASE
lib/model/Group.js
lib/services/groups/groupRegistryMongoDB.js
test/unit/provisioning/device-group-api-test.js

ADD static attributes to configuration

---

CHANGES_NEXT_RELEASE
README.md
lib/fiware-iotagent-lib.js
lib/plugins/addEvent.js
lib/plugins/pluginUtils.js
test/unit/examples/contextResponses/updateContextEvents1Success.json
test/unit/plugins/event-plugin_test.js

ADD Event plugins

---

CHANGES_NEXT_RELEASE
lib/services/devices/deviceRegistryMemory.js
test/unit/memoryRegistry/deviceRegistryMemory_test.js

FIX Device searching across multiple services

---

CHANGES_NEXT_RELEASE
lib/services/northBound/contextServer.js
test/unit/lazyAndCommands/active-devices-attribute-update-test.js
test/unit/lazyAndCommands/command-test.js
test/unit/lazyAndCommands/lazy-devices-test.js

FIX Pass service and subservice for handlers

---

CHANGES_NEXT_RELEASE
README.md
lib/services/groups/groupRegistryMongoDB.js

Update documentation with mandatory service and subservice

---

README.md
doc/Contribution.md

Contribution guidelines and version numnbers.

ADD Contribution guidelines to the repository

---

CHANGES_NEXT_RELEASE
lib/services/northBound/contextServer.js
test/unit/lazyAndCommands/command-test.js

FIX Mandatory update handler

---

CHANGES_NEXT_RELEASE
README.md
lib/commonConfig.js
lib/fiware-iotagent-lib.js
test/unit/general/startup-test.js

Configuration based on environment variables

---

.travis.yml

ADD New version of Node.js to Travis CI

ADD New version of Node.js to Travis CI

---

CHANGES_NEXT_RELEASE
lib/services/devices/deviceRegistryMongoDB.js
test/unit/mongodb/mongodb-registry-test.js

FIX Endpoint attribute not stored in Mongo

---

lib/services/devices/deviceRegistryMongoDB.js
test/unit/mongodb/mongodb-registry-test.js

FIX Missing transport attribute in MongoDB registry

FIX Missing transport attribute in MongoDB registry

---

CHANGES_NEXT_RELEASE
README.md
lib/commonConfig.js
test/unit/general/startup-test.js

FIX Prefix for environment variables

---

CHANGES_NEXT_RELEASE
README.md
lib/constants.js
lib/services/devices/deviceService.js
lib/services/ngsi/ngsiService.js
test/unit/examples/contextRequests/createProvisionedDevice.json
test/unit/examples/contextRequests/createProvisionedDeviceWithGroup.json
test/unit/examples/contextRequests/updateContextCommandError.json
test/unit/examples/contextRequests/updateContextCommandFinish.json
test/unit/examples/contextRequests/updateProvisionCommands1.json

FIX Name of the result field for commands

---

CHANGES_NEXT_RELEASE
lib/commonConfig.js
test/unit/general/startup-test.js

ADD New environment variables

---

npm-shrinkwrap.json
package.json

Prepare for next release

---

CHANGES_NEXT_RELEASE
lib/services/northBound/northboundServer.js

ADD Alternative path for version retrieval

---

CHANGES_NEXT_RELEASE
lib/services/common/genericMiddleware.js
lib/services/northBound/northboundServer.js
package.json
test/unit/general/loglevel-api_test.js

ADD Get log level API resource

---

CHANGES_NEXT_RELEASE
README.md
lib/fiware-iotagent-lib.js
test/unit/provisioning/device-group-api-test.js

ADD Component name in logs

---

README.md

ADD commenta about payload to DB correspondence

---

CHANGES_NEXT_RELEASE
lib/services/groups/groupRegistryMongoDB.js
lib/services/northBound/deviceGroupAdministrationServer.js
test/unit/examples/contextRequests/createProvisionedDeviceWithGroupAndStatic.json
test/unit/examples/contextRequests/updateContext3WithStatic.json
test/unit/mongodb/mongodb-group-registry-test.js
test/unit/provisioning/device-group-api-test.js
test/unit/provisioning/singleConfigurationMode-test.js

FIX Static attributes not shown in device groups

---

lib/services/common/iotManagerService.js
test/unit/examples/iotamRequests/registrationWithGroups.json
test/unit/examples/iotamRequests/registrationWithStaticGroups.json

Remove Command support for IOTAM registration (not currently supported in C++ IoTAM).

FIX Commands not supported by current IoTAM

---

CHANGES_NEXT_RELEASE
README.md
lib/commonConfig.js
lib/services/common/iotManagerService.js
lib/services/devices/deviceService.js
test/unit/general/iotam-autoregistration-test.js

Add configurable IoTA Path to the registration process for the IoTAM.

ADD Configuration variables for IoTA path in registration

---

lib/services/common/iotManagerService.js

FIX Default value for IOTA Path

FIX Default value for IOTA Path

---

CHANGES_NEXT_RELEASE
lib/services/devices/deviceService.js
lib/services/northBound/deviceProvisioningServer.js
test/unit/examples/contextRequests/updateProvisionDeviceStatic.json
test/unit/examples/deviceProvisioningRequests/updateDeviceStatic.json
test/unit/provisioning/updateProvisionedDevices-test.js

FIX Static attributes not working for updates

---

CHANGES_NEXT_RELEASE
README.md

ADD Documentation for the TimeInstant attribute semantics

---

CHANGES_NEXT_RELEASE
lib/services/devices/deviceRegistryMongoDB.js
lib/services/devices/deviceService.js
package.json

FIX missing attributes in update

FIX missing attributes in update

---

CHANGES_NEXT_RELEASE
lib/model/Device.js

FIX Remove Device ID index

---

CHANGES_NEXT_RELEASE
test/unit/mongodb/mongodb-registry-test.js
test/unit/provisioning/device-provisioning-api_test.js

ADD Tests for duplicate IDs

---

lib/plugins/multiEntity.js

FIX Check of active attributes in multientity plugin

---

CHANGES_NEXT_RELEASE
lib/model/Command.js
test/unit/lazyAndCommands/polling-commands-test.js

Multivalued commands allowed for polling commands.

FIX Multiple values for command

---

CHANGES_NEXT_RELEASE
doc/expressionLanguage.md

FIX Types in expression documentation

---

CHANGES_NEXT_RELEASE
lib/services/devices/deviceService.js
lib/services/ngsi/ngsiService.js
lib/services/northBound/restUtils.js
test/unit/examples/contextRequests/createTimeinstantDevice.json
test/unit/examples/contextResponses/createTimeinstantSuccess.json
test/unit/examples/deviceProvisioningRequests/provisionTimeInstant.json
test/unit/provisioning/device-provisioning-api_test.js

FIX Device with TimeInstant not allowed

---

CHANGES_NEXT_RELEASE
lib/templates/createDevice.json
lib/templates/updateDevice.json

FIX Wrong expression validation

---

CHANGES_NEXT_RELEASE
lib/services/northBound/deviceGroupAdministrationServer.js
test/unit/mongodb/mongodb-group-registry-test.js
test/unit/provisioning/device-group-api-test.js

FIX Return code for Group removal

---

CHANGES_NEXT_RELEASE
lib/constants.js
lib/services/commands/commandRegistryMemory.js
lib/services/commands/commandRegistryMongoDB.js
lib/services/commands/commandService.js
test/unit/examples/contextRequests/updateContextCommandExpired.json
test/unit/expressions/expression-test.js
test/unit/lazyAndCommands/polling-commands-test.js

FIX Mark expired command as errors

---

CHANGES_NEXT_RELEASE
lib/fiware-iotagent-lib.js

ADD Shared constants and errors

---

doc/operations.md

Updated operations manual to be included in the next library release

updated operations manual

---

CHANGES_NEXT_RELEASE
lib/services/common/alarmManagement.js
test/unit/general/alarmManagement-test.js

FIX alarm raised when callback called with null

---

README.md

you have some typos in readme links.

fixing broken links in readme

---

doc/howto.md

Hi!
In the call to iotAgentLib.getDevice some parameters are missing.
Set them to null.
Thanks for your great work!

Updated iotAgentLib.getDevice call

---

Gruntfile.js
lib/templates/updateDevice.json

ADD Allowed attribute

---

README.md

FIX broken link

---

package.json

Step: 2.5.0-next -> 2.6.0

---

CHANGES_NEXT_RELEASE
package.json

Same as PR https://github.com/telefonicaid/iotagent-node-lib/pull/564

Step: 2.6.0 -> 2.6.0-next

---

CHANGES_NEXT_RELEASE
README.md
examples/deviceGroup.json
examples/lwm2m-serviceActiveOMA.json
examples/lwm2m-servicePassiveOMA.json
test/unit/examples/groupProvisioningRequests/multipleGroupsCreation.json

*Edit:* fixes #588 
- Configuration API section fixed in README.md
- Incorrect examples fixed

Fixes Bug #588 (configuration API documentation)

---

CHANGES_NEXT_RELEASE
lib/services/devices/deviceService.js
lib/services/northBound/deviceProvisioningServer.js
test/unit/provisioning/device-provisioning-api_test.js

if device to be deleted is not found, immediately return 404.
fix https://github.com/telefonicaid/iotagent-ul/issues/249 & #587

fix callback when deleting a not existing device

---

CHANGES_NEXT_RELEASE
lib/services/groups/groupRegistryMongoDB.js
lib/services/northBound/deviceGroupAdministrationServer.js
test/unit/mongodb/mongodb-group-registry-test.js

This PR solves https://github.com/telefonicaid/iotagent-node-lib/issues/604.
It fixes some problems in groupService.js and groupRegistryMongoDB.js files.
The correctness of solution is demonstrated by adding a new test to mongodb-group-registry-test.js and modifying the expected value of another within this file.
Travis CI is passed and correct linting has been checked.

Repairs #604

---

CHANGES_NEXT_RELEASE
lib/plugins/timestampProcessPlugin.js
test/unit/ngsiv2/examples/contextRequests/updateContextMultientityTimestampPlugin1.json
test/unit/ngsiv2/plugins/multientity-plugin_test.js

This PR solves issue #621. The following changes have been done:
- New test added to detect the bug.
- Modification of timestampProcessPlugin to check if the input is an array and apply the functionality using map.

Fixes bug #621 to support timestampProcessPlugin to be executed after multientity plugin

---

CHANGES_NEXT_RELEASE
lib/plugins/multiEntity.js

Fix: https://github.com/telefonicaid/iotagent-node-lib/issues/627

fix multientity attributes duplicated in entity

---

CHANGES_NEXT_RELEASE
lib/plugins/multiEntity.js
lib/plugins/pluginUtils.js
test/unit/ngsiv2/examples/contextRequests/updateContextMultientityPlugin5.json
test/unit/ngsiv2/plugins/multientity-plugin_test.js

fix issue: https://github.com/telefonicaid/iotagent-node-lib/issues/635

handle multientity attributes with multiple measures

---

lib/services/common/alarmManagement.js

Reopen previous PR https://github.com/telefonicaid/iotagent-node-lib/pull/640/

(reopen) replace undefined by current alarm description: print alarm description as object

---

lib/commonConfig.js
lib/plugins/expressionParser.js

IOTA_AUTOCAST
IOTA_APPEND_MODE 
IOTA_SINGLE_MODE
Reopen PRs 
- https://github.com/telefonicaid/iotagent-node-lib/pull/619
- https://github.com/telefonicaid/iotagent-node-lib/pull/617

read boolean env vars checking  boolean values

---

package.json

Step: 2.6.0-next -> 2.7.0

---

CHANGES_NEXT_RELEASE
lib/services/devices/deviceRegistryMongoDB.js

Fix issue https://github.com/telefonicaid/iotagent-node-lib/issues/652

Ensure protocol in device provision

---

docker/Mosquitto/README.md

ADD README.md for mosquitto docker

---

doc/usermanual.md
package.json

Fixes a typo in doc a the npm lint script, based on what we have been discussed in https://github.com/telefonicaid/iotagent-json/pull/339#discussion_r230827354

Fix typo in doc and npm lint script

---

CHANGES_NEXT_RELEASE
doc/installationguide.md
lib/commonConfig.js

fix issue https://github.com/telefonicaid/iotagent-node-lib/issues/704

add missed auth conf env vars

---

CHANGES_NEXT_RELEASE
lib/errors.js
lib/services/ngsi/ngsiService.js
lib/services/northBound/restUtils.js
test/unit/ngsiService/active-devices-test.js
test/unit/ngsiv2/ngsiService/active-devices-test.js

Implements #679.
Unit tests have been added to demonstrate the new functionality for NGSIv1 and NGSIv2.

Checks ISO8601 format for timestamps

---

.jshintrc
.travis.yml
CHANGES_NEXT_RELEASE
lib/plugins/attributeAlias.js
lib/plugins/expressionParser.js
lib/plugins/expressionPlugin.js
lib/plugins/multiEntity.js
lib/plugins/pluginUtils.js
lib/services/devices/deviceRegistryMongoDB.js
lib/services/devices/deviceService.js
lib/services/devices/registrationUtils.js
lib/services/groups/groupService.js
lib/services/ngsi/ngsiService.js
package.json
test/.jshintrc
test/unit/provisioning/device-group-api-test.js
test/unit/provisioning/provisionDeviceMultientity-test.js

Currently, the code does not pass the linting check. I have fixed this issue and included `npm run lint` as part of Travis.

Corrects linting

---

CHANGES_NEXT_RELEASE
lib/services/common/iotManagerService.js
lib/services/devices/deviceService.js
lib/services/devices/registrationUtils.js
lib/services/ngsi/ngsiService.js
lib/services/ngsi/subscriptionService.js
test/unit/examples/iotamRequests/registrationWithGroups.json
test/unit/examples/iotamRequests/registrationWithStaticGroups.json
test/unit/ngsiv2/general/iotam-autoregistration-test.js

related manager fix https://github.com/telefonicaid/iotagent-manager/pull/158
related issue https://github.com/telefonicaid/iotagent-node-lib/issues/685

Use trust and cbHost from deviceGroup in typeInformation

---

test/unit/examples/contextRequests/updateContextTimestampOverrideWithoutMilis.json
test/unit/ngsiService/active-devices-test.js
test/unit/ngsiv2/examples/contextRequests/updateContextTimestampOverrideWithoutMilis.json
test/unit/ngsiv2/ngsiService/active-devices-test.js

~~Maybe the implementation in PR https://github.com/telefonicaid/iotagent-node-lib/pull/708 had some bug. This PR (when finished) attemps to solve it.~~
Adding 4 unit test to check ISO8601 happy path

unit test with ISO8601 checking happy path

---

doc/installationguide.md
lib/services/common/securityServiceOAuth2.js

Fixes https://github.com/telefonicaid/iotagent-node-lib/pull/726#discussion_r240737826 and https://github.com/telefonicaid/iotagent-node-lib/pull/726#discussion_r242123075

Address comments of PR #726

---

CHANGES_NEXT_RELEASE
doc/installationguide.md
lib/commonConfig.js
lib/services/common/securityServiceOAuth2.js
lib/services/devices/deviceService.js
lib/services/devices/registrationUtils.js
lib/services/ngsi/ngsiService.js
test/unit/examples/contextAvailabilityRequests/registerProvisionedDeviceWithGroup2.json
test/unit/examples/contextRequests/createProvisionedDeviceWithGroupAndStatic2.json
test/unit/examples/contextRequests/updateContext4.json
test/unit/examples/deviceProvisioningRequests/provisionNewDevice2.json
test/unit/examples/oauthRequests/getTokenFromTrustKeyrockGroup.json
test/unit/examples/oauthRequests/getTokenFromTrustKeyrockGroup2.json
test/unit/examples/oauthRequests/getTokenFromTrustKeyrockGroup3.json
test/unit/examples/oauthRequests/getTokenFromTrustKeyrockGroup4.json
test/unit/examples/oauthRequests/getTokenFromTrustKeyrockGroup5.json
test/unit/examples/oauthResponses/tokenFromTrustInvalidCredentialsKeyrock.json
test/unit/examples/oauthResponses/tokenFromTrustKeyrock.json
test/unit/examples/oauthResponses/tokenFromTrustKeyrock2.json
test/unit/examples/oauthResponses/tokenFromTrustKeyrock3.json
test/unit/examples/oauthResponses/tokenFromTrustKeyrock4.json
test/unit/examples/oauthResponses/tokenFromTrustKeyrock5.json
test/unit/examples/oauthResponses/tokenFromTrustUnauthorizedKeyrock.json
test/unit/ngsiv2/examples/contextAvailabilityRequests/registerProvisionedDeviceWithGroup2.json
test/unit/ngsiv2/examples/contextRequests/createProvisionedDeviceWithGroupAndStatic2.json
test/unit/ngsiv2/examples/contextRequests/updateContext1.json
test/unit/ngsiv2/examples/contextRequests/updateContext3WithStatic.json
test/unit/ngsiv2/examples/contextRequests/updateContext4.json
test/unit/ngsiv2/examples/contextResponses/queryContext1Success.json
test/unit/ngsiv2/general/contextBrokerOAuthSecurityAccess-test.js

Follow up of PR #664, in order to merge the OAuth2 implementation into master. You can check it is a mirror copy (same +- diff lines).
@jason-fox and @chicco785 were pending on (now closed) PR #664 so it would be great if they can provide feedback or LGTM in this PR.
CC: @dcalvoalonso

Support authentication with Oauth2 using FIWARE Keyrock IDM (to master)

---

package.json

Similar to PR https://github.com/telefonicaid/iotagent-node-lib/pull/651 (although the flush of CNR were already done in PR #729)

Step: 2.8.0 -> 2.8.0-next

---

CHANGES_NEXT_RELEASE
lib/plugins/multiEntity.js
test/unit/ngsiv2/examples/contextRequests/updateContextMultientityTimestampPlugin3.json
test/unit/ngsiv2/plugins/multientity-plugin_test.js

[WIP] Timestamp propagation to mapped entity

---

lib/services/ngsi/ngsiService.js
test/unit/ngsiv2/expressions/expressionBasedTransformations-test.js
test/unit/ngsiv2/general/contextBrokerOAuthSecurityAccess-test.js
test/unit/ngsiv2/ngsiService/active-devices-test.js
test/unit/ngsiv2/ngsiService/autocast-test.js
test/unit/ngsiv2/ngsiService/staticAttributes-test.js
test/unit/ngsiv2/plugins/alias-plugin_test.js
test/unit/ngsiv2/plugins/compress-timestamp-plugin_test.js
test/unit/ngsiv2/plugins/event-plugin_test.js
test/unit/ngsiv2/plugins/timestamp-processing-plugin_test.js

Add the ULR parameter "type" to specify the type in case of ambiguity when there are several entities with the same "id" but different types as described in the issue #733

 Add the "type" URL paramenter to sendUpdateValueNgsi2

---

CHANGES_NEXT_RELEASE
lib/services/devices/deviceService.js
lib/services/ngsi/ngsiService.js
test/unit/ngsiv2/general/contextBrokerOAuthSecurityAccess-test.js
test/unit/ngsiv2/plugins/compress-timestamp-plugin_test.js
test/unit/ngsiv2/provisioning/device-update-registration_test.js
test/unit/ngsiv2/provisioning/updateProvisionedDevices-test.js

This PR finishes the pending aspects of https://github.com/telefonicaid/iotagent-node-lib/pull/734/files#r249474148, which are related to https://github.com/telefonicaid/iotagent-node-lib/issues/733.
As requested in https://github.com/telefonicaid/iotagent-node-lib/issues/733#issuecomment-457157738, CNR entry has been added.

Add the "type" URL parameter to NGSIv2 queries

---

doc/expressionLanguage.md

Minor changes to fix some typos and header link

Fixed typo and header link

---

CHANGES_NEXT_RELEASE
lib/services/common/domain.js
lib/services/devices/deviceService.js
package.json

As https://github.com/telefonicaid/iotagent-node-lib/pull/526 comes from `unknown repository` and seems to have no activity, I have created a new PR with the same changes.

Finishes PR #526

---

CHANGES_NEXT_RELEASE
lib/command/migration.js
lib/model/dbConn.js
lib/services/commands/commandRegistryMongoDB.js
lib/services/devices/deviceRegistryMongoDB.js
lib/services/groups/groupRegistryMongoDB.js
lib/services/stats/statsRegistry.js
test/unit/general/migration-test.js
test/unit/general/statistics-persistence_test.js
test/unit/mongodb/mongoDBUtils.js
test/unit/mongodb/mongodb-group-registry-test.js
test/unit/mongodb/mongodb-registry-test.js

This PR solves the short term task of https://github.com/telefonicaid/iotagent-node-lib/blob/master/docs/roadmap.md:
> Removal of warnings and deprecation warnings.

Fix: removes warnings

---

package.json

Step: 2.9.0 -> 2.9.0-next

---

doc/installationguide.md

Updates installation guide for NGSIv2

---

package.json

Step: 2.10.0 -> 2.10.0-next

---

.travis.yml

Update .travis.yml attempting to avoid over-generating coverage reports on a single merge

---

CHANGES_NEXT_RELEASE
lib/commonConfig.js

Similar fix to PR #819 
I'm still wondering with this is not breaking current master (the bug has been raised in CI e2e with PR #815 but  not in master...).

FIX potential bug in process env vars logic

---

doc/howto.md
doc/installationguide.md

ADD warning about multi-cluster + bidirectionality in documentation

---

package.json

Step: 2.11.0 -> 2.11.0-next

---

.travis.yml
test/tools/utils.js

The *failure-to-load-a-file* error is occuring before any test is running and hence the number of failed tests=0.  Mocha completes, since no tests have failed this is interpreted as **success**. 
By amending the `readExampleFile()` utility function to catch all errors, attempting to load a non-existent file does not error - it just gives the wrong expectation and therefore should lead the test to fail.
Running
```console
mocha --recursive 'test/**/*.js' --reporter spec --timeout 3000 --ui bdd --exit
echo $?
```
Returns `0` so the test suite runs successfully even though the following error occurs:
```text
{ Error: ENOENT: no such file or directory, open './test/unit/examples/deviceProvisioningRequests/provisionAutoprovision.json'
at Object.fs.openSync (fs.js:646:18)
at …
```

Fix #812 Catch missing file failure and continue

---

CHANGES_NEXT_RELEASE
lib/errors.js
lib/services/ngsi/ngsiService.js
test/unit/examples/contextResponses/queryContext2Error.json
test/unit/examples/contextResponses/queryContext3Error.json
test/unit/ngsiService/queryDeviceInformationInCb-test.js

Fix for issue [IOTA UL- #199](https://github.com/telefonicaid/iotagent-ul/issues/199)
When a measure with unknown/undefined attribute is sent, it gives DEVICE_NOT_FOUND error but it should give ATTRIBUTE_NOT_FOUND error.

Updated files for error message fixing

---

lib/commonConfig.js

Remove sensitive information from plain-text output

Obfuscate password

---

CHANGES_NEXT_RELEASE
package.json

Step: 2.11.0-next -> 2.12.0

---

package.json

Step: 2.12.0 -> 2.12.0-next

---

docker/Mosquitto/Dockerfile

add websocket to mosquitto docker

---

CHANGES_NEXT_RELEASE
lib/fiware-iotagent-lib.js
lib/services/common/domain.js

Fixed for iotagent-json issue https://github.com/telefonicaid/iotagent-json/issues/426 : "Log always writes the same correlator and transaction id"

This PR is correspond to iotagent-json issue #426

---

CHANGES_NEXT_RELEASE
doc/api.md
doc/installationguide.md
lib/commonConfig.js
lib/model/Device.js
lib/model/Group.js
lib/services/common/iotManagerService.js
lib/services/devices/deviceRegistryMongoDB.js
lib/services/devices/deviceService.js
lib/services/groups/groupRegistryMongoDB.js
lib/services/ngsi/ngsiService.js
lib/services/northBound/deviceProvisioningServer.js
lib/templates/updateDevice.json
test/unit/examples/deviceProvisioningRequests/provisionExplicitAttrs.json
test/unit/examples/deviceProvisioningRequests/updateDeviceExplicitAttrs.json
test/unit/ngsiv2/examples/contextRequests/createExplicitAttrsDevice.json
test/unit/ngsiv2/provisioning/device-provisioning-api_test.js
test/unit/ngsiv2/provisioning/updateProvisionedDevices-test.js
test/unit/provisioning/device-group-api-test.js

The PR is common for both issues iotagent-json issue#416 and iotagent-ul issue#372 as "add feature: selectively ignore some measure"

Add feature selectively ignore some measure Issue/372

---

CHANGES_NEXT_RELEASE
lib/plugins/multiEntity.js

previously only 2 occurrences are working
fix for https://github.com/telefonicaid/iotagent-node-lib/issues/877

multientity plugin: allow multiple occurrences (more than 2)  of same attribute with same object_id

---

lib/constants.js

Fix related to review comment: https://github.com/telefonicaid/iotagent-node-lib/pull/849#discussion_r446045335

Make missing params public

---

CHANGES_NEXT_RELEASE
lib/services/devices/deviceRegistryMemory.js
lib/services/devices/deviceRegistryMongoDB.js
lib/services/devices/deviceService.js

fix issue https://github.com/telefonicaid/iotagent-node-lib/issues/889

do not raise alarm if device is not found at findOrCreate 

---

CHANGES_NEXT_RELEASE
lib/services/groups/groupRegistryMemory.js
lib/services/groups/groupRegistryMongoDB.js
lib/services/groups/groupService.js

fixes issue https://github.com/telefonicaid/iotagent-node-lib/issues/889#issuecomment-686524082

add get group silently; without raise alarm if not found

---

CHANGES_NEXT_RELEASE
lib/services/groups/groupRegistryMemory.js
test/unit/provisioning/device-group-api-test.js

Fixes the issue [IOTA-UL-391](https://github.com/telefonicaid/iotagent-ul/issues/391) for listing of service groups.

Updated file for fixing IOTAUL_issue391

---

lib/fiware-iotagent-lib.js

reopens https://github.com/telefonicaid/iotagent-node-lib/pull/896/

export deviceService.getDeviceSilently

---

doc/installationguide.md
lib/commonConfig.js
test/unit/ngsi-ld/general/config-jsonld-contexts-test.js

Even if the NGSI-LD specification encourages the use of a wrapper @context (it is only required when provided via a Link header), it is still informative and cases where contexts are provided as a list of URLs will happen.
This PR aims at handling this.

feat: allow to provide a list of JSON-LD @context

---

CHANGES_NEXT_RELEASE
lib/services/common/domain.js
lib/services/devices/deviceRegistryMongoDB.js
lib/services/groups/groupRegistryMongoDB.js
lib/services/ngsi/ngsiService.js
test/unit/ngsi-ld/general/config-jsonld-contexts-test.js

Merge branch 'master' into feature/842_ngsi_ld - fix conflicts again.

Fix merge conflicts again.

---

CHANGES_NEXT_RELEASE
package.json

Step: 2.12.0-next -> 2.13.0

---

package.json

Step: 2.13.0 -> 2.13.0-next

---

CHANGES_NEXT_RELEASE
lib/services/devices/deviceService.js
test/unit/examples/deviceProvisioningRequests/provisionStaticAttrsDevice.json
test/unit/examples/deviceProvisioningRequests/provisionStaticAttrsDevice2.json
test/unit/examples/deviceProvisioningRequests/provisionStaticAttrsDevice3.json
test/unit/ngsiv2/examples/contextRequests/createStaticAttributesProvisionDevice.json
test/unit/ngsiv2/examples/contextRequests/createStaticAttributesProvisionDevice2.json
test/unit/ngsiv2/examples/contextRequests/createStaticAttributesProvisionDevice3.json
test/unit/ngsiv2/provisioning/device-provisioning-api_test.js

Including Static Attributes in the request to store data at Database

---

CHANGES_NEXT_RELEASE
lib/errors.js
lib/services/devices/deviceService.js
lib/services/groups/groupRegistryMongoDB.js
package.json
test/unit/examples/deviceProvisioningRequests/provisionStaticAttrsDevice.json
test/unit/examples/deviceProvisioningRequests/provisionStaticAttrsDevice2.json
test/unit/examples/deviceProvisioningRequests/provisionStaticAttrsDevice3.json
test/unit/ngsiv2/examples/contextRequests/createStaticAttributesProvisionDevice.json
test/unit/ngsiv2/examples/contextRequests/createStaticAttributesProvisionDevice2.json
test/unit/ngsiv2/examples/contextRequests/createStaticAttributesProvisionDevice3.json
test/unit/ngsiv2/provisioning/device-provisioning-api_test.js

Merging https://github.com/telefonicaid/iotagent-node-lib/pull/908. into `master` caused another merge conflict.

Fix merge conflicts again again again.

---

CHANGES_NEXT_RELEASE
lib/commonConfig.js

It is called `IOTA_EXPLICIT_ATTRS` in the docs and elsewhere in the code.

Correct ENV variable name.

---

CHANGES_NEXT_RELEASE
lib/services/groups/groupRegistryMongoDB.js

fix issue https://github.com/telefonicaid/lightweightm2m-iotagent/issues/218

Add internalAttributes to update group

---

CHANGES_NEXT_RELEASE
lib/services/northBound/deviceProvisioningServer.js
lib/templates/createDevice.json
lib/templates/updateDevice.json

related https://github.com/telefonicaid/iotagent-json/issues/504

add mqtt {retain, qos}  to commands

---

CHANGES_NEXT_RELEASE
lib/services/common/iotManagerService.js
lib/services/devices/deviceService.js
test/unit/examples/iotamRequests/registrationWithGroups.json
test/unit/examples/iotamRequests/registrationWithGroupsWithoutCB.json
test/unit/examples/iotamRequests/registrationWithStaticGroups.json

related https://github.com/telefonicaid/iotagent-json/issues/508
fix for https://github.com/telefonicaid/iotagent-node-lib/issues/928

use group commands in devices and register it in iotamanager

---

CHANGES_NEXT_RELEASE
doc/installationguide.md
lib/commonConfig.js
lib/constants.js
lib/fiware-iotagent-lib.js
lib/model/Group.js
lib/services/common/domain.js
lib/services/common/iotManagerService.js
lib/services/devices/deviceService.js
lib/services/groups/groupRegistryMemory.js
lib/services/groups/groupRegistryMongoDB.js
lib/services/northBound/deviceProvisioningServer.js
lib/services/northBound/northboundServer.js
lib/templates/createDeviceLax.json
lib/templates/updateDeviceLax.json
test/unit/examples/iotamRequests/registrationWithGroups.json
test/unit/examples/iotamRequests/registrationWithGroupsWithoutCB.json
test/unit/examples/iotamRequests/registrationWithStaticGroups.json

Fix multiple merge conflicts. [sigh]

Fix merge conflicts again again again again.

---

package.json

Step: 2.14.0 -> 2.14.0-next

---

package.json

Related with https://github.com/telefonicaid/iotagent-json/pull/515#issuecomment-736355544

Removed textlint no dead link from package.json

---

lib/commonConfig.js

ADD FIXME mark

---

test/unit/ngsi-ld/examples/contextRequests/createProvisionedDeviceWithGroupAndStatic.json
test/unit/ngsi-ld/examples/contextRequests/createProvisionedDeviceWithGroupAndStatic2.json
test/unit/ngsi-ld/examples/contextRequests/createProvisionedDeviceWithGroupAndStatic3.json

Fixing requests

---

lib/templates/updateDevice.json

reopens https://github.com/telefonicaid/iotagent-node-lib/pull/976

add apikey to update device model

---

lib/services/ngsi/entities-NGSI-LD.js
test/unit/ngsi-ld/expressions/expressionBasedTransformations-test.js
test/unit/ngsi-ld/general/contextBrokerOAuthSecurityAccess-test.js
test/unit/ngsi-ld/lazyAndCommands/active-devices-attribute-update-test.js
test/unit/ngsi-ld/lazyAndCommands/command-test.js
test/unit/ngsi-ld/ngsiService/active-devices-test.js
test/unit/ngsi-ld/ngsiService/autocast-test.js
test/unit/ngsi-ld/ngsiService/geoproperties-test.js
test/unit/ngsi-ld/ngsiService/staticAttributes-test.js
test/unit/ngsi-ld/plugins/alias-plugin_test.js
test/unit/ngsi-ld/plugins/compress-timestamp-plugin_test.js
test/unit/ngsi-ld/plugins/event-plugin_test.js
test/unit/ngsi-ld/plugins/multientity-plugin_test.js
test/unit/ngsi-ld/plugins/timestamp-processing-plugin_test.js
test/unit/ngsi-mixed/provisioning/ngsi-versioning-test.js

Use   `/ngsi-ld/v1/entityOperations/upsert/?options=update` consistently
One line code change plus 15 updated test files

Fix #983 - add options=update

---

lib/services/northBound/contextServer-NGSI-LD.js
test/unit/ngsi-ld/lazyAndCommands/command-test.js
test/unit/ngsiv2/lazyAndCommands/command-test.js

Add test for multiple command handler calls for NGSI-v2 and NGSI-LD

Check command count

---

CHANGES_NEXT_RELEASE
lib/plugins/expressionParser.js
lib/plugins/jexlParser.js
lib/plugins/multiEntity.js

issue https://github.com/telefonicaid/iotagent-node-lib/issues/989

check and set proper expression plugin to use in multientity

---

package.json

Step: 2.15.0 -> 2.15.0-next

---

CHANGES_NEXT_RELEASE
lib/services/devices/deviceService.js
lib/services/devices/devices-NGSI-LD.js
lib/services/devices/devices-NGSI-mixed.js
lib/services/devices/devices-NGSI-v1.js
lib/services/devices/devices-NGSI-v2.js
lib/services/northBound/deviceProvisioningServer.js
test/unit/examples/contextAvailabilityRequests/updateCommands1.json
test/unit/examples/contextAvailabilityRequests/updateIoTAgent1.json
test/unit/examples/contextAvailabilityRequests/updateIoTAgent3.json
test/unit/examples/contextRequests/updateActiveAttributes.json
test/unit/examples/contextRequests/updateProvisionDevice.json
test/unit/examples/contextResponses/updateActiveAttributesSuccess.json
test/unit/ngsi-ld/provisioning/device-update-registration_test.js
test/unit/ngsi-ld/provisioning/updateProvisionedDevices-test.js
test/unit/ngsiv2/examples/contextAvailabilityRequests/updateCommands1.json
test/unit/ngsiv2/examples/contextAvailabilityRequests/updateIoTAgent1.json
test/unit/ngsiv2/provisioning/device-update-registration_test.js
test/unit/ngsiv2/provisioning/updateProvisionedDevices-test.js
test/unit/provisioning/device-update-registration_test.js

update entity_type and entity_name of devices

---

CHANGES_NEXT_RELEASE
lib/services/ngsi/entities-NGSI-v1.js

Fix for issue https://github.com/telefonicaid/iotagent-node-lib/issues/1003#issue-829138778

Fix for Issue# 1003

---

lib/services/groups/groupService.js

was always printing [Object object] instead of real object

Update log  groupService.js

---

CHANGES_NEXT_RELEASE
lib/services/devices/deviceService.js

related https://github.com/telefonicaid/iotagent-node-lib/issues/1007

get silently checking duplicates

---

CHANGES_NEXT_RELEASE
lib/commonConfig.js
lib/services/ngsi/subscription-NGSI-LD.js
test/unit/ngsi-ld/examples/subscriptionRequests/bidirectionalSubscriptionRequest.json
test/unit/ngsi-ld/examples/subscriptionRequests/simpleSubscriptionRequest.json
test/unit/ngsi-ld/examples/subscriptionRequests/simpleSubscriptionRequest2.json
test/unit/ngsi-ld/general/config-jsonld-contexts-test.js

There was a bug in the NGSI-LD subscription handling - this PR corrects the content type, includes the `@context` and updates the payload.

Bug fix: Include @context on subscription

---

CHANGES_NEXT_RELEASE
lib/services/devices/deviceService.js
lib/services/devices/devices-NGSI-v2.js

fix for https://github.com/telefonicaid/iotagent-node-lib/issues/1027

use expresionLanguage from group if not defined

---

lib/services/devices/deviceRegistryMongoDB.js

Any update over a device is rejected due to is trying insert it as a new document
comes from https://github.com/telefonicaid/iotagent-node-lib/pull/999/

allow update a device

---

lib/plugins/expressionParser.js

related https://github.com/telefonicaid/iotagent-node-lib/issues/1031

log legacy expression parser error

---

CHANGES_NEXT_RELEASE
lib/plugins/multiEntity.js
lib/services/northBound/contextServer-NGSI-v2.js

jexl applyExpression could return NaN
fix for https://github.com/telefonicaid/iotagent-node-lib/issues/1039

check entityId is valid after apply expression in multientity plugin

---

lib/services/ngsi/entities-NGSI-v2.js

Reopens previous PR
No CNR update is needed.

add missed callback

---

CHANGES_NEXT_RELEASE
doc/expressionLanguage.md
lib/plugins/jexlParser.js

issue https://github.com/telefonicaid/iotagent-node-lib/issues/1052

add more functions to jexl transformations

---

lib/services/ngsi/ngsiUtils.js

FIX getErrorFieldV2 export

---

doc/api.md

fix link to reverse (bidirectional) expression documentation

fix documentation link to bidirectional data mapping plugin

---

package.json

Mimics PR https://github.com/telefonicaid/iotagent-node-lib/pull/993

Step: 2.16.0 -> 2.16.0-next

---

lib/plugins/jexlParser.js

Renamed sumarray to addreduce

---

CHANGES_NEXT_RELEASE
doc/expressionLanguage.md
lib/plugins/jexlParser.js

rename sumaarray jexl function to addreduce

---

CHANGES_NEXT_RELEASE
doc/api.md
lib/services/devices/deviceService.js

issue reported https://github.com/telefonicaid/iotagent-node-lib/issues/1076
related with PR https://github.com/telefonicaid/iotagent-node-lib/pull/1010/

findByType and then findWihtoutType if no group is found

---

doc/advanced-topics.md

Taking advantage of some bits from PR https://github.com/telefonicaid/perseo-fe/pull/543

FIX improve docu related with trust tokens

---

CHANGES_NEXT_RELEASE
package.json

Step: 2.16.0-next -> 2.17.0

---

package.json

Step: 2.17.0 -> 2.17.0-next

---

doc/advanced-topics.md

Mimics similar changes to the ones in PR https://github.com/telefonicaid/perseo-fe/pull/544

FIX improve docu

---

CHANGES_NEXT_RELEASE
lib/services/devices/deviceRegistryMongoDB.js

fix for https://github.com/telefonicaid/iotagent-node-lib/issues/1092

include internalAttributes

---

docker/Mosquitto/startMosquitto.sh

FIX improve auth exclusion

---

.github/workflows/ci.yml

Issue #1021 
iotagent-manager was missing in PR #1103
CC: @jason-fox

ADD missing repository to dispach list

---

.github/workflows/ci.yml

Run if a push occurs to master - tested here: https://github.com/jason-fox/sigfox-iotagent/runs/3599537922

Simplify dispatch test

---

test/unit/general/contextBrokerKeystoneSecurityAccess-test.js

This was spotted in PR #995 but I didn't want to stop the merge for so little thing ;)
CC: @jason-fox

REMOVE leftover comment

---

CHANGES_NEXT_RELEASE
lib/services/northBound/deviceProvisioningServer.js

fix for https://github.com/telefonicaid/iotagent-node-lib/issues/1115

Include attribute metadata in attribute device info

---

CHANGES_NEXT_RELEASE
lib/plugins/pluginUtils.js
lib/services/ngsi/entities-NGSI-v2.js
package.json
test/unit/ngsi-ld/examples/contextRequests/updateContextMultientityTimestampPlugin1.json
test/unit/ngsi-ld/examples/contextRequests/updateContextMultientityTimestampPlugin2.json
test/unit/ngsiv2/examples/contextRequests/updateContextMultientityPlugin11.json
test/unit/ngsiv2/examples/contextRequests/updateContextMultientityTimestampPlugin1.json
test/unit/ngsiv2/examples/contextRequests/updateContextMultientityTimestampPlugin2.json
test/unit/ngsiv2/ngsiService/active-devices-test.js
test/unit/ngsiv2/plugins/multientity-plugin_test.js

clean PR version of https://github.com/telefonicaid/iotagent-node-lib/pull/1125
issue https://github.com/telefonicaid/iotagent-node-lib/issues/1124

Fix/wrong id type use as attrs #1124 

---

lib/plugins/pluginUtils.js
lib/services/ngsi/entities-NGSI-v2.js
package.json
test/unit/ngsiv2/examples/contextRequests/updateContextMultientityPlugin11.json
test/unit/ngsiv2/ngsiService/active-devices-test.js
test/unit/ngsiv2/plugins/multientity-plugin_test.js

WIP Ignore Wrong attrs #1124

---

lib/plugins/multiEntity.js

PR for branch fix/multientity_same_name 
related with PR  https://github.com/telefonicaid/iotagent-node-lib/pull/1128

Fix/multientity same name filter: filterByAttributeObjectIds with args

---

CHANGES_NEXT_RELEASE
lib/plugins/pluginUtils.js
lib/services/ngsi/entities-NGSI-v2.js
test/unit/ngsi-ld/examples/contextRequests/updateContextMultientityTimestampPlugin1.json
test/unit/ngsi-ld/examples/contextRequests/updateContextMultientityTimestampPlugin2.json
test/unit/ngsiv2/examples/contextRequests/updateContextMultientityTimestampPlugin1.json
test/unit/ngsiv2/examples/contextRequests/updateContextMultientityTimestampPlugin2.json

this PR is the same than https://github.com/telefonicaid/iotagent-node-lib/pull/1130 (that was reverted) but after merge https://github.com/telefonicaid/iotagent-node-lib/pull/1135

Fix/wrong id type use as attrs #1124

---

CHANGES_NEXT_RELEASE
lib/plugins/jexlParser.js
lib/plugins/multiEntity.js
test/unit/expressions/jexlExpression-test.js
test/unit/ngsiv2/examples/contextRequests/updateContextExpressionPlugin31.json
test/unit/ngsiv2/expressions/jexlBasedTransformations-test.js

this PR is the same of PR https://github.com/telefonicaid/iotagent-node-lib/pull/1133  (that was reverted) 
but this PR was done after merge https://github.com/telefonicaid/iotagent-node-lib/pull/1135

Fix wrong JEXL null/undefined management #1132

---

test/unit/ngsiv2/examples/contextRequests/updateContextMultientityPlugin11.json
test/unit/ngsiv2/plugins/multientity-plugin_test.js

missed tests code from PRs
https://github.com/telefonicaid/iotagent-node-lib/pull/1130
https://github.com/telefonicaid/iotagent-node-lib/pull/1128
https://github.com/telefonicaid/iotagent-node-lib/pull/1133/

add missed test after merge

---

package.json

Step: 2.18.0 -> 2.18.0-next

---

doc/expressionLanguage.md

Add some notes regarding casting expressionLanguage.md + typos

---

CHANGES_NEXT_RELEASE
lib/services/ngsi/ngsiService.js

fix for issue https://github.com/telefonicaid/iotagent-node-lib/issues/1155

try get group by type using current type if no type is provided

---

doc/expressionLanguage.md

This PR is intended to rework the expression language documentation in order to prioritize JEXL language, adapt ToC, etc

Rework Expression Language doc

---

doc/expressionLanguage.md

FIX expression documentation

---

docker/Mosquitto/startMosquitto.sh

fix for https://github.com/telefonicaid/iotagent-node-lib/issues/1161

fix: use provided username in aclfile 

---

CHANGES_NEXT_RELEASE

```diff
- ADD: allow update polling devide field (iota-json#602)
+ ADD: allow update polling device field (iota-json#602)
```

FIX CNR typo

---

test/unit/mongodb/mongodb-registry-test.js
test/unit/ngsi-ld/general/contextBrokerOAuthSecurityAccess-test.js
test/unit/ngsi-ld/ngsiService/subscriptions-test.js
test/unit/ngsi-ld/plugins/bidirectional-plugin_test.js
test/unit/ngsi-ld/provisioning/device-registration_test.js
test/unit/ngsi-ld/provisioning/removeProvisionedDevice-test.js
test/unit/ngsi-ld/provisioning/updateProvisionedDevices-test.js
test/unit/ngsiv2/general/contextBrokerOAuthSecurityAccess-test.js
test/unit/ngsiv2/ngsiService/subscriptions-test.js
test/unit/ngsiv2/plugins/bidirectional-plugin_test.js
test/unit/ngsiv2/provisioning/device-group-api-test.js
test/unit/ngsiv2/provisioning/device-registration_test.js
test/unit/ngsiv2/provisioning/device-update-registration_test.js
test/unit/ngsiv2/provisioning/removeProvisionedDevice-test.js
test/unit/ngsiv2/provisioning/updateProvisionedDevices-test.js

Add empty body expectation check for DELETE mocks

---

CHANGES_NEXT_RELEASE
lib/plugins/expressionParser.js
test/unit/ngsiv2/examples/contextRequests/updateContextExpressionPlugin17.json
test/unit/ngsiv2/expressions/expressionBasedTransformations-test.js

issue https://github.com/telefonicaid/iotagent-node-lib/issues/1191

add underscore to expression parser legacy

---

package.json

prepare 2.19-next: Step: 2.19.0 -> 2.19.0-next

---

CHANGES_NEXT_RELEASE
package.json

Mimics PR https://github.com/telefonicaid/iotagent-node-lib/pull/1199

Step: 2.19.0-next -> 2.20.0

---

package.json

Mimics PR https://github.com/telefonicaid/iotagent-node-lib/pull/1144

Step: 2.20.0 -> 2.20.0-next

---

CHANGES_NEXT_RELEASE
lib/services/devices/deviceRegistryMemory.js
lib/services/devices/deviceRegistryMongoDB.js
lib/services/devices/deviceService.js
lib/services/northBound/contextServer-NGSI-v2.js

fix for https://github.com/telefonicaid/iotagent-node-lib/issues/1211

fix: search device and group for a command using entity type when provided

---

lib/fiware-iotagent-lib.js

reopens https://github.com/telefonicaid/iotagent-node-lib/pull/1212

exports getDeviceByNameAndType

---

CHANGES_NEXT_RELEASE
lib/services/northBound/contextServerUtils.js

fix for https://github.com/telefonicaid/iotagent-node-lib/issues/1216

fix bad query searching for group using resource instead of type

---

doc/api.md

Realized of this while reviewing PR https://github.com/telefonicaid/iotagent-node-lib/pull/1209
As far as I understand the attribute configurations applies to groups and devices.

FIX api.md

---

lib/plugins/expressionPlugin.js

reopens previos PR https://github.com/telefonicaid/iotagent-node-lib/pull/1225

Exclude processing all attrs expression when current attr to update is of type commandStatus of commandResult (reopen)

---

CHANGES_NEXT_RELEASE
package.json

upgrade moment version dep due to security vulnerability

---

CHANGES_NEXT_RELEASE
package.json

Step: 2.20.0-next -> 2.21.0

---

package.json

Step: 2.21.0 -> 2.22.0-next

---

CHANGES_NEXT_RELEASE
lib/plugins/expressionPlugin.js
lib/plugins/multiEntity.js

At command exectuions typeInformation is just device (without group information)

set jexl as default parser

---

CHANGES_NEXT_RELEASE
doc/advanced-topics.md
lib/services/ngsi/entities-NGSI-v2.js
test/unit/ngsiv2/expressions/jexlBasedTransformations-test.js

Feature and documentation added.

Feature #1267 extend explicit attrs

---

CHANGES_NEXT_RELEASE
test/unit/memoryRegistry/deviceRegistryMemory_test.js
test/unit/mongodb/mongodb-group-registry-test.js
test/unit/mongodb/mongodb-registry-test.js

This PR fixes the issue: https://github.com/telefonicaid/iotagent-node-lib/issues/1213

UT test case to check device and group based on name and type entity

---

CHANGES_NEXT_RELEASE
lib/services/devices/deviceService.js

Add entityNameExp=="" management,
fix logic for default naming,
add exception control  for bad JEXL expression

improve entityNameExp

---

package.json

Step: 2.24.0 -> 2.24.0-next

---

CHANGES_NEXT_RELEASE
lib/plugins/jexlParser.js
test/unit/ngsi-ld/examples/contextRequests/updateContextExpressionPlugin30.json
test/unit/ngsi-ld/expressions/jexlBasedTransformations-test.js
test/unit/ngsiv2/examples/contextRequests/updateContextMultientityJexlExpressionPlugin1.json
test/unit/ngsiv2/expressions/jexlBasedTransformations-test.js
test/unit/ngsiv2/plugins/multientity-plugin_test.js

1 LD test is not passing
Issue #1292

Avoid Exception on expression check

---

CHANGES_NEXT_RELEASE
doc/expressionLanguage.md
lib/jexlTranformsMap.js
test/unit/expressions/jexlExpression-test.js

PR https://github.com/telefonicaid/iotagent-node-lib/pull/1304 re-done
(except the link to the playground, that I think is obsolete and should be re-generated from scratch)
CC: @danielvillalbamota

ADD two new jexl transformations

---

package.json

Step: 2.25.0 -> 2.25.0-next

---

CHANGES_NEXT_RELEASE
package.json

Step: 2.26.0-next -> 3.0.0

---

doc/api.md

This PR is part of #1332 
This PR concludes changes in API Routes. Further changes in order to link and improve the information here with the topics will be made in subsequents PRs

[Doc Rework] [API] API Routes

---

CHANGES_NEXT_RELEASE
lib/services/ngsi/entities-NGSI-LD.js
lib/services/ngsi/entities-NGSI-v2.js
test/unit/ngsiv2/examples/contextRequests/updateContextExpressionPlugin32.json
test/unit/ngsiv2/examples/contextRequests/updateContextProcessTimestamp.json
test/unit/ngsiv2/examples/contextRequests/updateContextTimestampOverride.json
test/unit/ngsiv2/examples/contextRequests/updateContextTimestampOverrideWithoutMilis.json
test/unit/ngsiv2/ngsiService/active-devices-test.js

propage TimeInstant to all metatata when is provided ad measure  for al lcases

[HOTFIX] propage TimeInstant to all metatata when is provided ad measure 

---

CHANGES_NEXT_RELEASE
lib/services/ngsi/entities-NGSI-LD.js
lib/services/ngsi/entities-NGSI-v2.js
test/unit/ngsiv2/examples/contextRequests/updateContextExpressionPlugin32.json
test/unit/ngsiv2/examples/contextRequests/updateContextProcessTimestamp.json
test/unit/ngsiv2/examples/contextRequests/updateContextTimestampOverride.json
test/unit/ngsiv2/examples/contextRequests/updateContextTimestampOverrideWithoutMilis.json
test/unit/ngsiv2/ngsiService/active-devices-test.js

Related https://github.com/telefonicaid/iotagent-node-lib/pull/1343

 Fix/propage timestamp as measure all metadata all cases [master]

---

CHANGES_NEXT_RELEASE
package.json

Step: 3.0.0-next -> 3.1.0

---

package.json

Step: 3.1.0 -> 3.1.0-next

---

CHANGES_NEXT_RELEASE
lib/templates/createDevice.json
lib/templates/createDeviceLax.json

An attribute entity_name like `Device + ':' + Type` where rejected

Fix/device attribute entity_name validation

---

CHANGES_NEXT_RELEASE
lib/services/ngsi/entities-NGSI-v2.js

that characters where introduced by https://github.com/telefonicaid/iotagent-node-lib/issues/1342

remove new line from logs of sendUpdateValueNgsi2

---

lib/plugins/jexlParser.js

This PR solves how this file is imported in Agents.

Change how `jexlParser.js` import private JEXL files

---

CHANGES_NEXT_RELEASE
doc/api.md
lib/jexlTranformsMap.js

https://github.com/telefonicaid/iotagent-node-lib/issues/1367

add hextostring transformation jexl function

---

package.json

step 3.2.0 -> 3.2.0-next

---

doc/api.md

Comes from: 
https://github.com/telefonicaid/iotagent-ul/issues/216#issuecomment-1590810453

Improve Append Mode doc

---

CHANGES_NEXT_RELEASE
config.js
doc/api.md
doc/installationguide.md
lib/services/ngsi/entities-NGSI-LD.js
lib/services/ngsi/entities-NGSI-v2.js

related with PRs: https://github.com/telefonicaid/iotagent-node-lib/pull/1111
https://github.com/telefonicaid/iotagent-node-lib/pull/1382

appendMode true by default

---

CHANGES_NEXT_RELEASE
lib/model/Device.js
lib/model/Group.js
lib/services/common/iotManagerService.js
lib/services/devices/deviceRegistryMongoDB.js
lib/services/devices/deviceService.js
lib/services/devices/devices-NGSI-v2.js
lib/services/northBound/deviceProvisioningServer.js
lib/templates/createDevice.json
lib/templates/createDeviceLax.json
lib/templates/deviceGroup.json
test/unit/examples/deviceProvisioningRequests/provisionMinimumDevice4.json
test/unit/ngsiv2/plugins/multientity-plugin_test.js
test/unit/ngsiv2/provisioning/device-provisioning-api_test.js

https://github.com/telefonicaid/iotagent-node-lib/issues/1384

fully remove expression language field

---

CHANGES_NEXT_RELEASE
doc/api.md
lib/services/devices/deviceService.js
lib/services/ngsi/entities-NGSI-v2.js

Issue https://github.com/telefonicaid/iotagent-node-lib/issues/1334
Depends on https://github.com/telefonicaid/iotagent-node-lib/pull/1111

Evaluate group entityNameExp with a context including measures

---

lib/services/devices/deviceRegistryMongoDB.js

continuation of PR https://github.com/telefonicaid/iotagent-node-lib/pull/1393/
No CNR update is needed,

allow update device timestamp

---

CHANGES_NEXT_RELEASE
config.js
doc/api.md
doc/deprecated.md
doc/howto.md
doc/installationguide.md

Deprecate bidirectional plugin and appendMode

---

doc/api.md

Retreive loglevel changed to GET in docs

---

CHANGES_NEXT_RELEASE
lib/services/ngsi/entities-NGSI-v2.js
test/unit/ngsiv2/examples/contextRequests/updateContextExpressionPlugin1.json
test/unit/ngsiv2/examples/contextRequests/updateContextExpressionPlugin11.json
test/unit/ngsiv2/examples/contextRequests/updateContextExpressionPlugin12.json
test/unit/ngsiv2/examples/contextRequests/updateContextExpressionPlugin2.json
test/unit/ngsiv2/examples/contextRequests/updateContextExpressionPlugin29.json
test/unit/ngsiv2/examples/contextRequests/updateContextExpressionPlugin3.json
test/unit/ngsiv2/examples/contextRequests/updateContextExpressionPlugin41.json
test/unit/ngsiv2/examples/contextRequests/updateContextExpressionPlugin5.json
test/unit/ngsiv2/examples/contextRequests/updateContextExpressionPlugin6.json
test/unit/ngsiv2/examples/contextRequests/updateContextExpressionPlugin7.json
test/unit/ngsiv2/examples/contextRequests/updateContextExpressionPlugin8.json
test/unit/ngsiv2/examples/contextRequests/updateContextExpressionPlugin9.json
test/unit/ngsiv2/examples/contextRequests/updateContextMultientityPlugin25.json
test/unit/ngsiv2/expressions/jexlBasedTransformations-test.js

Fix for https://github.com/telefonicaid/iotagent-node-lib/issues/1440

fix for non evaluable expressions which should not be progress to attrs values

---

CHANGES_NEXT_RELEASE
package.json

Mimics https://github.com/telefonicaid/iotagent-node-lib/pull/1414

step 3.3.0-next -> 3.4.0

---

package.json

step 3.4.0 -> 3.4.0-next

---

test/unit/ngsi-ld/examples/contextRequests/createProvisionedDeviceWithGroupAndStatic2.json
test/unit/ngsi-ld/general/contextBrokerOAuthSecurityAccess-test.js
test/unit/ngsi-ld/lazyAndCommands/command-test.js
test/unit/ngsi-ld/lazyAndCommands/merge-patch-test.js
test/unit/ngsi-ld/lazyAndCommands/polling-commands-test.js
test/unit/ngsi-ld/ngsiService/subscriptions-test.js
test/unit/ngsi-ld/provisioning/device-provisioning-api_test.js
test/unit/ngsi-ld/provisioning/device-registration_test.js
test/unit/ngsi-ld/provisioning/device-update-registration_test.js
test/unit/ngsi-ld/provisioning/singleConfigurationMode-test.js
test/unit/ngsi-ld/provisioning/updateProvisionedDevices-test.js

Fixes #1447 - this is just updating the test expectations and removing the initial CB insert.

Fix NGSI-LD test

---

CHANGES_NEXT_RELEASE
lib/services/ngsi/entities-NGSI-v2.js

fix for https://github.com/telefonicaid/iotagent-node-lib/issues/1493 and all cases of tests https://github.com/telefonicaid/iotagent-node-lib/pull/1490

update ctxt with current attribute value after apply expression

---

doc/api.md
test/unit/ngsiv2/expressions/jexlBasedTransformations-test.js

Should take the array order defined to apply expressions

Add nested expressions test + doc

---

CHANGES_NEXT_RELEASE
lib/services/common/genericMiddleware.js

 ensure service and subservice in context of error handlers using req headers

---

CHANGES_NEXT_RELEASE
lib/plugins/expressionPlugin.js
lib/plugins/jexlParser.js

This code should be deleted when bidirectional code was deleted

remove extractVariables

---

doc/api.md
test/unit/ngsiv2/expressions/jexlBasedTransformations-test.js

Completes doc changes at https://github.com/telefonicaid/iotagent-node-lib/pull/1494 and include doc tests

Improve nested expressions doc and include more tests

---

test/unit/ngsiv2/ngsiService/staticAttributes-test.js

This PR includes `explicitAttrs` + `staticAttributes` tests

Add static attrs + explicit tests

---

doc/index.md

Fix_For_Broken_Link

---

package.json

step 4.0.0 -> 4.0.0-next

---

test/functional/functional-tests-runner.js

Twin PR: https://github.com/telefonicaid/iotagent-json/pull/785

Fix skipping at should level

---

CHANGES_NEXT_RELEASE
package.json

Mimics PR https://github.com/telefonicaid/iotagent-node-lib/pull/1533

step 4.0.0-next -> 4.1.0

---

package.json

step 4.1.0 -> 4.1.0-next

---

.readthedocs.yml

Align with https://github.com/telefonicaid/fiware-orion/blob/master/.readthedocs.yml

FIX .readthedocs.yml

---

CHANGES_NEXT_RELEASE
package.json

step 4.1.0-next -> 4.2.0

---

package.json

step 4.2.0 -> 4.2.0-next

---

CHANGES_NEXT_RELEASE
test/functional/testCases.js
test/functional/testUtils.js

Changed type from string to Text

---

CHANGES_NEXT_RELEASE
package.json

step 4.2.0-next -> 4.3.0

---

package.json

step 4.3.0 -> 4.3.0-next

---

CHANGES_NEXT_RELEASE
lib/commonConfig.js
lib/services/ngsi/ngsiService.js

issue https://github.com/telefonicaid/iotagent-node-lib/issues/1594 and rationale https://github.com/telefonicaid/iotagent-node-lib/issues/1594#issuecomment-2039201693

reduce information showed handling errors to just config flags

---

CHANGES_NEXT_RELEASE
doc/api.md
lib/services/ngsi/entities-NGSI-v2.js
test/functional/testCases.js

related https://github.com/telefonicaid/iotagent-node-lib/issues/1598

add metadata in attributes and static_attributes test cases and process metadata jexl expressions

---

package.json

step 4.4.0 -> 4.4.0-next

---

CHANGES_NEXT_RELEASE
config.js
doc/admin.md
lib/commonConfig.js
lib/services/northBound/northboundServer.js

related https://github.com/telefonicaid/iotagent-json/issues/827+
This PR is increasing default value for express limit from 100Kb to 1Mb

allow change default express limit

---

CHANGES_NEXT_RELEASE
package.json

step 4.4.0-next -> 4.5.0 

---

package.json

step 4.5.0 -> 4.5.0-next

---

doc/admin.md
doc/api.md
doc/devel/architecture.md
doc/devel/development.md
doc/getting-started.md

[Doc] Rename service groups or configurations to config groups

---

package.json

step 4.6.0 -> 4.6.0-next

---

test/unit/general/config-multi-core-test.js
test/unit/ngsi-ld/expressions/jexlBasedTransformations-test.js
test/unit/ngsi-ld/general/config-jsonld-contexts-test.js
test/unit/ngsiv2/expressions/jexlBasedTransformations-test.js

issue https://github.com/telefonicaid/iotagent-node-lib/issues/1679

remove throttling: 'PT5S'

---

package.json

step 4.7.0 -> 4.7.0-next

---

CHANGES_NEXT_RELEASE
lib/jexlTranformsMap.js
test/unit/expressions/jexlExpression-test.js

This PR was initially intended to add try-catch blocks to some functions, but it also includes additional test cases and suggests better error handling. Referenced Issue: #1701

 Error control in JEXL transformations

---

test/functional/testUtils.js

Related with (and probably fixes) https://github.com/telefonicaid/iotagent-json/issues/782#issuecomment-1825350053

add typeInformation to testUtils of functional tests

---

package.json

Mimics PR https://github.com/telefonicaid/iotagent-node-lib/pull/1695

step 4.8.0 -> 4.8.0-next

---

Changelog

Based in https://github.com/telefonicaid/iotagent-node-lib/releases

ADD full Changelog file

---

CHANGES_NEXT_RELEASE
Changelog
package.json

step 4.8.0-next -> 4.9.0

---

.github/workflows/ci.yml
CHANGES_NEXT_RELEASE
package.json

FIX node20 as minimum version
